import { OptionTypes, PreferredCarriers, BankRoutingNumbers, StatesAbbreviation } from '../types/formData';

export const relationshipOptions: OptionTypes[] = [
  {
    label: 'Aunt',
    value: 'Aunt',
  },
  {
    label: 'Brother-in-law',
    value: 'Brother-in-law',
  },
  {
    label: 'Business Partner',
    value: 'Business Partner',
  },
  {
    label: 'Child',
    value: 'Child',
  },
  {
    label: 'Common Law Spouse',
    value: 'Common Law Spouse',
  },
  {
    label: 'Cousin',
    value: 'Cousin',
  },
  {
    label: 'Custodian under UTMA/UGMA',
    value: 'Custodian UTMA/UGMA',
  },
  {
    label: 'Daughter-in-law',
    value: 'Daughter-in-law',
  },
  {
    label: 'Domestic Partner',
    value: 'Domestic Partner',
  },
  {
    label: 'Ex-spouse',
    value: 'Ex-spouse',
  },
  {
    label: 'Father-in-law',
    value: 'Father-in-law',
  },
  {
    label: 'Fiance',
    value: 'Fiance',
  },
  {
    label: 'Friend',
    value: 'Friend',
  },
  {
    label: 'Grandchild',
    value: 'Grandchild',
  },
  {
    label: 'Grandparent',
    value: 'Grandparent',
  },
  {
    label: 'Mother-in-law',
    value: 'Mother-in-law',
  },
  {
    label: 'Nephew',
    value: 'Nephew',
  },
  {
    label: 'Niece',
    value: 'Niece',
  },
  {
    label: 'Parent',
    value: 'Parent',
  },
  {
    label: 'Sibling',
    value: 'Sibling',
  },
  {
    label: 'Sister-in-law',
    value: 'Sister-in-law',
  },
  {
    label: 'Son-in-law',
    value: 'Son-in-law',
  },
  {
    label: 'Spouse',
    value: 'Spouse',
  },
  {
    label: 'Step Parent',
    value: 'Step Parent',
  },
  {
    label: 'Stepchild',
    value: 'Step Child',
  },
  {
    label: 'Step Sibling',
    value: 'Step Sibling',
  },
  {
    label: 'Uncle',
    value: 'Uncle',
  },
];

export const statesAbbreviation: StatesAbbreviation = {
  alabama: 'AL',
  alaska: 'AK',
  arizona: 'AZ',
  arkansas: 'AR',
  california: 'CA',
  colorado: 'CO',
  connecticut: 'CT',
  delaware: 'DE',
  florida: 'FL',
  georgia: 'GA',
  hawaii: 'HI',
  idaho: 'ID',
  illinois: 'IL',
  indiana: 'IN',
  iowa: 'IA',
  kansas: 'KS',
  kentucky: 'KY',
  louisiana: 'LA',
  maine: 'ME',
  maryland: 'MD',
  massachusetts: 'MA',
  michigan: 'MI',
  minnesota: 'MN',
  mississippi: 'MS',
  missouri: 'MO',
  montana: 'MT',
  nebraska: 'NE',
  nevada: 'NV',
  new_hampshire: 'NH',
  new_jersey: 'NJ',
  new_mexico: 'NM',
  new_york: 'NY',
  north_Carolina: 'NC',
  north_dakota: 'ND',
  ohio: 'OH',
  oklahoma: 'OK',
  oregon: 'OR',
  pennsylvania: 'PA',
  rhode_island: 'RI',
  south_carolina: 'SC',
  south_dakota: 'SD',
  tennessee: 'TN',
  texas: 'TX',
  utah: 'UT',
  vermont: 'VT',
  virginia: 'VA',
  washington: 'WA',
  west_virginia: 'WV',
  wisconsin: 'WI',
  wyoming: 'WY',
  puerto_rico: 'PR',
};

export const unitedStates: OptionTypes[] = [
  { label: 'Alabama - AL', value: 'alabama' },
  { label: 'Alaska - AK', value: 'alaska' },
  { label: 'Arizona - AZ', value: 'arizona' },
  { label: 'Arkansas - AR', value: 'arkansas' },
  { label: 'California - CA', value: 'california' },
  { label: 'Colorado - CO', value: 'colorado' },
  { label: 'Connecticut - CT', value: 'connecticut' },
  { label: 'Delaware - DE', value: 'delaware' },
  { label: 'Florida - FL', value: 'florida' },
  { label: 'Georgia - GA', value: 'georgia' },
  { label: 'Hawaii - HI', value: 'hawaii' },
  { label: 'Idaho - ID', value: 'idaho' },
  { label: 'Illinois - IL', value: 'illinois' },
  { label: 'Indiana - IN', value: 'indiana' },
  { label: 'Iowa - IA', value: 'iowa' },
  { label: 'Kansas - KS', value: 'kansas' },
  { label: 'Kentucky - KY', value: 'kentucky' },
  { label: 'Louisiana - LA', value: 'louisiana' },
  { label: 'Maine - ME', value: 'maine' },
  { label: 'Maryland - MD', value: 'maryland' },
  { label: 'Massachusetts - MA', value: 'massachusetts' },
  { label: 'Michigan - MI', value: 'michigan' },
  { label: 'Minnesota - MN', value: 'minnesota' },
  { label: 'Mississippi - MS', value: 'mississippi' },
  { label: 'Missouri - MO', value: 'missouri' },
  { label: 'Montana - MT', value: 'montana' },
  { label: 'Nebraska - NE', value: 'nebraska' },
  { label: 'Nevada - NV', value: 'nevada' },
  { label: 'New Hampshire - NH', value: 'new_hampshire' },
  { label: 'New Jersey - NJ', value: 'new_jersey' },
  { label: 'New Mexico - NM', value: 'new_mexico' },
  { label: 'New York - NY', value: 'new_york' },
  { label: 'North Carolina - NC', value: 'north_Carolina' },
  { label: 'North Dakota - ND', value: 'north_dakota' },
  { label: 'Ohio - OH', value: 'ohio' },
  { label: 'Oklahoma - OK', value: 'oklahoma' },
  { label: 'Oregon - OR', value: 'oregon' },
  { label: 'Pennsylvania - PA', value: 'pennsylvania' },
  { label: 'Rhode Island - RI', value: 'rhode_island' },
  { label: 'South Carolina - SC', value: 'south_carolina' },
  { label: 'South Dakota - SD', value: 'south_dakota' },
  { label: 'Tennessee - TN', value: 'tennessee' },
  { label: 'Texas - TX', value: 'texas' },
  { label: 'Utah - UT', value: 'utah' },
  { label: 'Vermont - VT', value: 'vermont' },
  { label: 'Virginia - VA', value: 'virginia' },
  { label: 'Washington - WA', value: 'washington' },
  { label: 'West Virginia - WV', value: 'west_virginia' },
  { label: 'Wisconsin - WI', value: 'wisconsin' },
  { label: 'Wyoming - WY', value: 'wyoming' },
  { label: 'Puerto Rico - PR', value: 'puerto_rico' },
];

export const preferredCarriers: PreferredCarriers = {
  alabama: ['Aetna', 'UnitedHealthcare (UHC)'],
  alaska: ['None'],
  arizona: ['Aetna', 'Ambetter', 'Cigna', 'Oscar', 'UnitedHealthcare (UHC)'],
  arkansas: ['None'],
  california: ['Aetna', 'Molina', 'Oscar'],
  colorado: ['Cigna', 'Friday Health Plans', 'Oscar', 'UnitedHealthcare (UHC)'],
  connecticut: ['None'],
  delaware: ['None'],
  florida: ['Aetna', 'Ambetter', 'Avmed', 'Cigna', 'Florida Blue', 'Molina', 'Oscar', 'UnitedHealthcare (UHC)'],
  georgia: ['Ambetter', 'Cigna', 'Friday Health Plans', 'Oscar', 'UnitedHealthcare (UHC)'],
  hawaii: ['None'],
  idaho: ['None'],
  illinois: ['Aetna', 'Ambetter', 'Cigna', 'Molina', 'Oscar', 'UnitedHealthcare (UHC)'],
  indiana: ['Aetna', 'Ambetter'],
  iowa: ['Oscar'],
  kansas: ['Aetna', 'Cigna', 'Oscar'],
  kentucky: ['None'],
  louisiana: ['Ambetter', 'UnitedHealthcare (UHC)'],
  maine: ['None'],
  maryland: ['UnitedHealthcare (UHC)'],
  massachusetts: ['None'],
  michigan: ['Aetna', 'Ambetter', 'Molina', 'Oscar', 'UnitedHealthcare (UHC)'],
  minnesota: ['None'],
  mississippi: ['Ambetter', 'Cigna', 'Molina', 'UnitedHealthcare (UHC)'],
  missouri: ['Cigna', 'Oscar', 'UnitedHealthcare (UHC)'],
  montana: ['None'],
  nebraska: ['Ambetter', 'Oscar'],
  nevada: ['None'],
  new_hampshire: ['None'],
  new_jersey: ['Aetna', 'Ambetter', 'Oscar', 'UnitedHealthcare (UHC)'],
  new_mexico: ['Aetna', 'Ambetter', 'Friday Health Plans', 'Molina'],
  new_york: ['None'],
  north_Carolina: ['Aetna', 'Ambetter', 'Cigna', 'Friday Health Plans', 'Oscar', 'UnitedHealthcare (UHC)'],
  north_dakota: ['None'],
  ohio: ['Aetna', 'Ambetter', 'Molina', 'Oscar', 'UnitedHealthcare (UHC)'],
  oklahoma: ['Aetna', 'Ambetter', 'Friday Health Plans', 'Oscar', 'UnitedHealthcare (UHC)'],
  oregon: ['None'],
  pennsylvania: ['Cigna', 'Oscar'],
  rhode_island: ['None'],
  south_carolina: ['Aetna', 'Ambetter', 'BlueCross BlueShield', 'Cigna', 'Molina', 'UnitedHealthcare (UHC)'],
  south_dakota: ['None'],
  tennessee: ['Aetna', 'Ambetter', 'Oscar', 'UnitedHealthcare (UHC)'],
  texas: [
    'Aetna',
    'Ambetter',
    'BlueCross BlueShield',
    'Cigna',
    'Friday Health Plans',
    'Molina',
    'Oscar',
    'UnitedHealthcare (UHC)',
  ],
  utah: ['Aetna', 'Cigna', 'Molina', 'UnitedHealthcare (UHC)'],
  vermont: ['None'],
  virginia: ['Aetna', 'Cigna', 'Oscar', 'UnitedHealthcare (UHC)'],
  washington: ['None'],
  west_virginia: ['None'],
  wisconsin: ['None'],
  wyoming: ['None'],
  puerto_rico: ['None'],
};

export const countries: OptionTypes[] = [
  {
    label: 'United States Of America',
    value: 'United States Of America',
  },
  {
    label: 'Albania',
    value: 'Albania',
  },
  {
    label: 'Algeria',
    value: 'Algeria',
  },
  {
    label: 'Andorra',
    value: 'Andorra',
  },
  {
    label: 'Angola',
    value: 'Angola',
  },
  {
    label: 'Anguilla',
    value: 'Anguilla',
  },
  {
    label: 'Antigua And Barbuda',
    value: 'Antigua And Barbuda',
  },
  {
    label: 'Arab Emirates',
    value: 'Arab Emirates',
  },
  {
    label: 'Argentina',
    value: 'Argentina',
  },
  {
    label: 'Armenia',
    value: 'Armenia',
  },
  {
    label: 'Aruba',
    value: 'Aruba',
  },
  {
    label: 'Australia',
    value: 'Australia',
  },
  {
    label: 'Austria',
    value: 'Austria',
  },
  {
    label: 'Azerbaijan',
    value: 'Azerbaijan',
  },
  {
    label: 'The Bahamas',
    value: 'The Bahamas',
  },
  {
    label: 'Bahrain',
    value: 'Bahrain',
  },
  {
    label: 'Bangladesh',
    value: 'Bangladesh',
  },
  {
    label: 'Barbados',
    value: 'Barbados',
  },
  {
    label: 'Belarus',
    value: 'Belarus',
  },
  {
    label: 'Belgium',
    value: 'Belgium',
  },
  {
    label: 'Belize',
    value: 'Belize',
  },
  {
    label: 'Bermuda',
    value: 'Bermuda',
  },
  {
    label: 'Bolivia',
    value: 'Bolivia',
  },
  {
    label: 'Bosnia And Herzegovina',
    value: 'Bosnia And Herzegovina',
  },
  {
    label: 'Botswana',
    value: 'Botswana',
  },
  {
    label: 'Brazil',
    value: 'Brazil',
  },
  {
    label: 'Brunei',
    value: 'Brunei',
  },
  {
    label: 'Bulgaria',
    value: 'Bulgaria',
  },
  {
    label: 'Cambodia',
    value: 'Cambodia',
  },
  {
    label: 'Cameroon',
    value: 'Cameroon',
  },
  {
    label: 'Canada',
    value: 'Canada',
  },
  {
    label: 'Cayman Islands',
    value: 'Cayman Islands',
  },
  {
    label: 'Chad',
    value: 'Chad',
  },
  {
    label: 'Chile',
    value: 'Chile',
  },
  {
    label: 'China,Hong Kong S.A.R.',
    value: 'China,Hong Kong S.A.R.',
  },
  {
    label: 'China P.Rep.',
    value: 'China P.Rep.',
  },
  {
    label: 'Cocos Islands',
    value: 'Cocos Islands',
  },
  {
    label: 'Colombia',
    value: 'Colombia',
  },
  {
    label: 'Congo, Democratic Republic Of',
    value: 'Congo, Democratic Republic Of',
  },
  {
    label: 'Cook Islands',
    value: 'Cook Islands',
  },
  {
    label: 'Costa Rica',
    value: 'Costa Rica',
  },
  {
    label: 'Croatia',
    value: 'Croatia',
  },
  {
    label: 'Cuba',
    value: 'Cuba',
  },
  {
    label: 'Cyprus',
    value: 'Cyprus',
  },
  {
    label: 'Czech Republic',
    value: 'Czech Republic',
  },
  {
    label: 'Czechoslovakia',
    value: 'Czechoslovakia',
  },
  {
    label: 'Denmark',
    value: 'Denmark',
  },
  {
    label: 'Dominica',
    value: 'Dominica',
  },
  {
    label: 'Dominican Repl.',
    value: 'Dominican Repl.',
  },
  {
    label: 'Ecuador',
    value: 'Ecuador',
  },
  {
    label: 'Egypt',
    value: 'Egypt',
  },
  {
    label: 'El Salvador',
    value: 'El Salvador',
  },
  {
    label: 'Estonia',
    value: 'Estonia',
  },
  {
    label: 'Ethiopia',
    value: 'Ethiopia',
  },
  {
    label: 'Falkland Islands(Malvinas)',
    value: 'Falkland Islands(Malvinas)',
  },
  {
    label: 'Faroe Islands',
    value: 'Faroe Islands',
  },
  {
    label: 'Fiji',
    value: 'Fiji',
  },
  {
    label: 'Finland',
    value: 'Finland',
  },
  {
    label: 'Fr. Polynesia',
    value: 'Fr. Polynesia',
  },
  {
    label: 'French Guiana',
    value: 'French Guiana',
  },
  {
    label: 'France',
    value: 'France',
  },
  {
    label: 'Gambia',
    value: 'Gambia',
  },
  {
    label: 'Gabon',
    value: 'Gabon',
  },
  {
    label: 'Georgia(Republic Of)',
    value: 'Georgia(Republic Of)',
  },
  {
    label: 'Germany',
    value: 'Germany',
  },
  {
    label: 'Ghana',
    value: 'Ghana',
  },
  {
    label: 'Gibraltar',
    value: 'Gibraltar',
  },
  {
    label: 'Greece',
    value: 'Greece',
  },
  {
    label: 'Greenland',
    value: 'Greenland',
  },
  {
    label: 'Grenada',
    value: 'Grenada',
  },
  {
    label: 'Guadeloupe',
    value: 'Guadeloupe',
  },
  {
    label: 'Guatemala',
    value: 'Guatemala',
  },
  {
    label: 'Guinea',
    value: 'Guinea',
  },
  {
    label: 'Guyana',
    value: 'Guyana',
  },
  {
    label: 'Haiti',
    value: 'Haiti',
  },
  {
    label: 'Honduras',
    value: 'Honduras',
  },
  {
    label: 'Hungary',
    value: 'Hungary',
  },
  {
    label: 'Iceland',
    value: 'Iceland',
  },
  {
    label: 'India',
    value: 'India',
  },
  {
    label: 'Indonesia',
    value: 'Indonesia',
  },
  {
    label: 'Iran',
    value: 'Iran',
  },
  {
    label: 'Iraq',
    value: 'Iraq',
  },
  {
    label: 'Ireland',
    value: 'Ireland',
  },
  {
    label: 'Israel',
    value: 'Israel',
  },
  {
    label: 'Italy',
    value: 'Italy',
  },
  {
    label: 'Cote d Ivoire',
    value: 'Cote d Ivoire',
  },
  {
    label: 'Jamaica',
    value: 'Jamaica',
  },
  {
    label: 'Japan',
    value: 'Japan',
  },
  {
    label: 'Jordan',
    value: 'Jordan',
  },
  {
    label: 'Kazakhstan',
    value: 'Kazakhstan',
  },
  {
    label: 'Kenya',
    value: 'Kenya',
  },
  {
    label: 'Kuwait',
    value: 'Kuwait',
  },
  {
    label: 'Kyrgyzstan',
    value: 'Kyrgyzstan',
  },
  {
    label: 'Laos',
    value: 'Laos',
  },
  {
    label: 'Latvia',
    value: 'Latvia',
  },
  {
    label: 'Lebanon',
    value: 'Lebanon',
  },
  {
    label: 'Liberia',
    value: 'Liberia',
  },
  {
    label: 'Libya',
    value: 'Libya',
  },
  {
    label: 'Liechtenstein',
    value: 'Liechtenstein',
  },
  {
    label: 'Lithuania',
    value: 'Lithuania',
  },
  {
    label: 'Luxembourg',
    value: 'Luxembourg',
  },
  {
    label: 'Macau',
    value: 'Macau',
  },
  {
    label: 'Macedonia, Former Yugoslav Rep.',
    value: 'Macedonia, Former Yugoslav Rep.',
  },
  {
    label: 'Madagascar',
    value: 'Madagascar',
  },
  {
    label: 'Malawi',
    value: 'Malawi',
  },
  {
    label: 'Malaysia',
    value: 'Malaysia',
  },
  {
    label: 'Mali',
    value: 'Mali',
  },
  {
    label: 'Malta',
    value: 'Malta',
  },
  {
    label: 'Marshall Islands',
    value: 'Marshall Islands',
  },
  {
    label: 'Martinique',
    value: 'Martinique',
  },
  {
    label: 'Mauritania',
    value: 'Mauritania',
  },
  {
    label: 'Mauritius',
    value: 'Mauritius',
  },
  {
    label: 'Mexico',
    value: 'Mexico',
  },
  {
    label: 'Moldova, Republic Of',
    value: 'Moldova, Republic Of',
  },
  {
    label: 'Monaco',
    value: 'Monaco',
  },
  {
    label: 'Morocco',
    value: 'Morocco',
  },
  {
    label: 'Myanmar',
    value: 'Myanmar',
  },
  {
    label: 'Namibia',
    value: 'Namibia',
  },
  {
    label: 'Nepal',
    value: 'Nepal',
  },
  {
    label: 'Neth. Antilles',
    value: 'Neth. Antilles',
  },
  {
    label: 'Netherlands',
    value: 'Netherlands',
  },
  {
    label: 'New Caledonia',
    value: 'New Caledonia',
  },
  {
    label: 'New Guinea',
    value: 'New Guinea',
  },
  {
    label: 'New Zealand',
    value: 'New Zealand',
  },
  {
    label: 'Nicaragua',
    value: 'Nicaragua',
  },
  {
    label: 'Niger',
    value: 'Niger',
  },
  {
    label: 'Nigeria',
    value: 'Nigeria',
  },
  {
    label: 'Norfolk Island',
    value: 'Norfolk Island',
  },
  {
    label: 'North Korea',
    value: 'North Korea',
  },
  {
    label: 'Norway',
    value: 'Norway',
  },
  {
    label: 'Oman',
    value: 'Oman',
  },
  {
    label: 'Pakistan',
    value: 'Pakistan',
  },
  {
    label: 'Panama',
    value: 'Panama',
  },
  {
    label: 'Paraguay',
    value: 'Paraguay',
  },
  {
    label: 'Peru',
    value: 'Peru',
  },
  {
    label: 'Philippines',
    value: 'Philippines',
  },
  {
    label: 'Poland',
    value: 'Poland',
  },
  {
    label: 'Portugal',
    value: 'Portugal',
  },
  {
    label: 'Palau',
    value: 'Palau',
  },
  {
    label: 'Qatar',
    value: 'Qatar',
  },
  {
    label: 'Romania',
    value: 'Romania',
  },
  {
    label: 'Russian Federation',
    value: 'Russian Federation',
  },
  {
    label: 'Saint Kitts And Nevis',
    value: 'Saint Kitts And Nevis',
  },
  {
    label: 'San Marino',
    value: 'San Marino',
  },
  {
    label: 'Saudi Arabia',
    value: 'Saudi Arabia',
  },
  {
    label: 'Senegal',
    value: 'Senegal',
  },
  {
    label: 'Sierra Leone',
    value: 'Sierra Leone',
  },
  {
    label: 'Singapore',
    value: 'Singapore',
  },
  {
    label: 'Slovakia',
    value: 'Slovakia',
  },
  {
    label: 'Slovenia',
    value: 'Slovenia',
  },
  {
    label: 'Solomon Islands',
    value: 'Solomon Islands',
  },
  {
    label: 'South Africa',
    value: 'South Africa',
  },
  {
    label: 'South Korea',
    value: 'South Korea',
  },
  {
    label: 'Spain',
    value: 'Spain',
  },
  {
    label: 'Sri Lanka',
    value: 'Sri Lanka',
  },
  {
    label: 'St. Lucia',
    value: 'St. Lucia',
  },
  {
    label: 'St. Vincent/Grenadines',
    value: 'St. Vincent/Grenadines',
  },
  {
    label: 'Sudan',
    value: 'Sudan',
  },
  {
    label: 'Suriname',
    value: 'Suriname',
  },
  {
    label: 'Swaziland',
    value: 'Swaziland',
  },
  {
    label: 'Sweden',
    value: 'Sweden',
  },
  {
    label: 'Switzerland',
    value: 'Switzerland',
  },
  {
    label: 'Syria',
    value: 'Syria',
  },
  {
    label: 'Taiwan',
    value: 'Taiwan',
  },
  {
    label: 'Tanzania',
    value: 'Tanzania',
  },
  {
    label: 'Thailand',
    value: 'Thailand',
  },
  {
    label: 'Trinidad/Tobago',
    value: 'Trinidad/Tobago',
  },
  {
    label: 'Tunisia',
    value: 'Tunisia',
  },
  {
    label: 'Turkey',
    value: 'Turkey',
  },
  {
    label: 'Turks And Caicos Islands',
    value: 'Turks And Caicos Islands',
  },
  {
    label: 'Uganda',
    value: 'Uganda',
  },
  {
    label: 'Ukraine',
    value: 'Ukraine',
  },
  {
    label: 'United Kingdom',
    value: 'United Kingdom',
  },
  {
    label: 'Uruguay',
    value: 'Uruguay',
  },
  {
    label: 'Uzbekistan',
    value: 'Uzbekistan',
  },
  {
    label: 'Vanuatu(New Hebrides)',
    value: 'Vanuatu(New Hebrides)',
  },
  {
    label: 'Vatican City State(Holy See)',
    value: 'Vatican City State(Holy See)',
  },
  {
    label: 'Venezuela',
    value: 'Venezuela',
  },
  {
    label: 'Viet Nam',
    value: 'Viet Nam',
  },
  {
    label: 'Virgin(British) Islands',
    value: 'Virgin(British) Islands',
  },
  {
    label: 'Yemen',
    value: 'Yemen',
  },
  {
    label: 'Zambia',
    value: 'Zambia',
  },
  {
    label: 'Zimbabwe',
    value: 'Zimbabwe',
  },
  {
    label: 'Other Alien',
    value: 'Other Alien',
  },
  {
    label: 'Afghanistan',
    value: 'Afghanistan',
  },
  {
    label: 'Åland Islands',
    value: 'Åland Islands',
  },
  {
    label: 'Antarctica',
    value: 'Antarctica',
  },
  {
    label: 'Benin',
    value: 'Benin',
  },
  {
    label: 'Bhutan',
    value: 'Bhutan',
  },
  {
    label: 'Bouvet Island',
    value: 'Bouvet Island',
  },
  {
    label: 'British Indian Ocean Territory',
    value: 'British Indian Ocean Territory',
  },
  {
    label: 'Burkina Faso',
    value: 'Burkina Faso',
  },
  {
    label: 'Burundi',
    value: 'Burundi',
  },
  {
    label: 'Cape Verde',
    value: 'Cape Verde',
  },
  {
    label: 'Central African Republic',
    value: 'Central African Republic',
  },
  {
    label: 'Christmas Island',
    value: 'Christmas Island',
  },
  {
    label: 'Comoros',
    value: 'Comoros',
  },
  {
    label: 'Djibouti',
    value: 'Djibouti',
  },
  {
    label: 'Equatorial Guinea',
    value: 'Equatorial Guinea',
  },
  {
    label: 'Eritrea',
    value: 'Eritrea',
  },
  {
    label: 'French Southern Territories',
    value: 'French Southern Territories',
  },
  {
    label: 'Guernsey',
    value: 'Guernsey',
  },
  {
    label: 'Guinea-Bissau',
    value: 'Guinea-Bissau',
  },
  {
    label: 'Heard and McDonald Islands',
    value: 'Heard and McDonald Islands',
  },
  {
    label: 'Isle of Man',
    value: 'Isle of Man',
  },
  {
    label: 'Jersey',
    value: 'Jersey',
  },
  {
    label: 'Kiribati',
    value: 'Kiribati',
  },
  {
    label: 'Lesotho',
    value: 'Lesotho',
  },
  {
    label: 'Maldives',
    value: 'Maldives',
  },
  {
    label: 'Mayotte',
    value: 'Mayotte',
  },
  {
    label: 'Micronesia, Federated States Of',
    value: 'Micronesia, Federated States Of',
  },
  {
    label: 'Mongolia',
    value: 'Mongolia',
  },
  {
    label: 'Montenegro',
    value: 'Montenegro',
  },
  {
    label: 'Montserrat',
    value: 'Montserrat',
  },
  {
    label: 'Mozambique',
    value: 'Mozambique',
  },
  {
    label: 'Nauru',
    value: 'Nauru',
  },
  {
    label: 'Niue',
    value: 'Niue',
  },
  {
    label: 'Palestinian Territory, Occupied',
    value: 'Palestinian Territory, Occupied',
  },
  {
    label: 'Pitcairn',
    value: 'Pitcairn',
  },
  {
    label: 'Réunion',
    value: 'Réunion',
  },
  {
    label: 'Rwanda',
    value: 'Rwanda',
  },
  {
    label: 'Saint Barthélemy',
    value: 'Saint Barthélemy',
  },
  {
    label: 'Saint Helena, Ascension and Tristan Da Cunha',
    value: 'Saint Helena, Ascension and Tristan Da Cunha',
  },
  {
    label: 'Saint Martin',
    value: 'Saint Martin',
  },
  {
    label: 'Saint Pierre And Miquelon',
    value: 'Saint Pierre And Miquelon',
  },
  {
    label: 'Sao Tome and Principe',
    value: 'Sao Tome and Principe',
  },
  {
    label: 'Serbia',
    value: 'Serbia',
  },
  {
    label: 'Seychelles',
    value: 'Seychelles',
  },
  {
    label: 'Somalia',
    value: 'Somalia',
  },
  {
    label: 'South Georgia and the South Sandwich Islands',
    value: 'South Georgia and the South Sandwich Islands',
  },
  {
    label: 'Svalbard And Jan Mayen',
    value: 'Svalbard And Jan Mayen',
  },
  {
    label: 'Tajikistan',
    value: 'Tajikistan',
  },
  {
    label: 'Timor-Leste',
    value: 'Timor-Leste',
  },
  {
    label: 'Togo',
    value: 'Togo',
  },
  {
    label: 'Tokelau',
    value: 'Tokelau',
  },
  {
    label: 'Tonga',
    value: 'Tonga',
  },
  {
    label: 'Turkmenistan',
    value: 'Turkmenistan',
  },
  {
    label: 'Tuvalu',
    value: 'Tuvalu',
  },
  {
    label: 'United States Minor Outlying Islands',
    value: 'United States Minor Outlying Islands',
  },
  {
    label: 'Wallis and Futuna',
    value: 'Wallis and Futuna',
  },
  {
    label: 'Western Sahara',
    value: 'Western Sahara',
  },
  {
    label: 'Congo',
    value: 'Congo',
  },
  {
    label: 'Curacao',
    value: 'Curacao',
  },
  {
    label: 'SINT MAARTEN(DUTCH PART)',
    value: 'SINT MAARTEN(DUTCH PART)',
  },
  {
    label: 'Samoa',
    value: 'Samoa',
  },
  {
    label: 'Bonaire',
    value: 'Bonaire',
  },
];

export const employmentOptions: OptionTypes[] = [
  {
    label: 'Employed',
    value: 'Employed',
  },
  {
    label: 'Disabled',
    value: 'Disabled',
  },
  {
    label: 'Student',
    value: 'Student',
  },
  {
    label: 'Retired',
    value: 'Retired',
  },
  {
    label: 'Stay-at-home',
    value: 'Stay-at-home',
  },
  {
    label: 'Unemployed',
    value: 'Unemployed',
  },
];

export const occupations: OptionTypes[] = [
  {
    label: 'Accountant',
    value: 'Accountant',
  },
  {
    label: 'Actor',
    value: 'Actor',
  },
  {
    label: 'Actuary',
    value: 'Actuary',
  },
  {
    label: 'Administrator',
    value: 'Administrator',
  },
  {
    label: 'Administrator or Educational Office',
    value: 'Administrator or Educational Office',
  },
  {
    label: 'Aerobics instructor',
    value: 'Aerobics instructor',
  },
  {
    label: 'Aesthetician',
    value: 'Aesthetician',
  },
  {
    label: 'Agricultural engineer or technician',
    value: 'Agricultural engineer or technician',
  },
  {
    label: 'Agricultural equipment operator',
    value: 'Agricultural equipment operator',
  },
  {
    label: 'Agricultural inspector',
    value: 'Agricultural inspector',
  },
  {
    label: 'Agricultural worker',
    value: 'Agricultural worker',
  },
  {
    label: 'Air Marshal',
    value: 'Air Marshal',
  },
  {
    label: 'Air traffic controller',
    value: 'Air traffic controller',
  },
  {
    label: 'Aircraft mechanic and service technician',
    value: 'Aircraft mechanic and service technician',
  },
  {
    label: 'Aircraft pilot',
    value: 'Aircraft pilot',
  },
  {
    label: 'Aircraft structure assembler',
    value: 'Aircraft structure assembler',
  },
  {
    label: 'Ambulance driver',
    value: 'Ambulance driver',
  },
  {
    label: 'Amusement and recreation attendant',
    value: 'Amusement and recreation attendant',
  },
  {
    label: 'Animal breeder',
    value: 'Animal breeder',
  },
  {
    label: 'Animal Control',
    value: 'Animal Control',
  },
  {
    label: 'Animal control worker',
    value: 'Animal control worker',
  },
  {
    label: 'Animal scientist',
    value: 'Animal scientist',
  },
  {
    label: 'Animal trainer',
    value: 'Animal trainer',
  },
  {
    label: 'Animator',
    value: 'Animator',
  },
  {
    label: 'Announcer',
    value: 'Announcer',
  },
  {
    label: 'Antenna installer and repairer',
    value: 'Antenna installer and repairer',
  },
  {
    label: 'Anthropologist',
    value: 'Anthropologist',
  },
  {
    label: 'Appraiser or estimator',
    value: 'Appraiser or estimator',
  },
  {
    label: 'Arbitrator, mediator, and conciliator',
    value: 'Arbitrator, mediator, and conciliator',
  },
  {
    label: 'Arborist',
    value: 'Arborist',
  },
  {
    label: 'Arcade employee',
    value: 'Arcade employee',
  },
  {
    label: 'Archeologist',
    value: 'Archeologist',
  },
  {
    label: 'Architect',
    value: 'Architect',
  },
  {
    label: 'Archivist, Curator or Museum Technician',
    value: 'Archivist, Curator or Museum Technician',
  },
  {
    label: 'Armored Car Driver',
    value: 'Armored Car Driver',
  },
  {
    label: 'Art director',
    value: 'Art director',
  },
  {
    label: 'Artist or related worker',
    value: 'Artist or related worker',
  },
  {
    label: 'Asbestos, Lead Hazardous materials worker',
    value: 'Asbestos, Lead Hazardous materials worker',
  },
  {
    label: 'Asphalt, Paving equipment worker',
    value: 'Asphalt, Paving equipment worker',
  },
  {
    label: 'Assembler and fabricator',
    value: 'Assembler and fabricator',
  },
  {
    label: 'Astronaut',
    value: 'Astronaut',
  },
  {
    label: 'Astronomer',
    value: 'Astronomer',
  },
  {
    label: 'Athletes and Sports Competitor',
    value: 'Athletes and Sports Competitor',
  },
  {
    label: 'Athletic trainer',
    value: 'Athletic trainer',
  },
  {
    label: 'Audio and video equipment technician',
    value: 'Audio and video equipment technician',
  },
  {
    label: 'Audio Visual Specialist',
    value: 'Audio Visual Specialist',
  },
  {
    label: 'Audiologist',
    value: 'Audiologist',
  },
  {
    label: 'Auditor',
    value: 'Auditor',
  },
  {
    label: 'Author',
    value: 'Author',
  },
  {
    label: 'Auto Sales, New',
    value: 'Auto Sales, New',
  },
  {
    label: 'Auto Sales, Used',
    value: 'Auto Sales, Used',
  },
  {
    label: 'Automobile stunt or speed testing driver',
    value: 'Automobile stunt or speed testing driver',
  },
  {
    label: 'Automotive body painter or repairer',
    value: 'Automotive body painter or repairer',
  },
  {
    label: 'Automotive glass installer and repairer',
    value: 'Automotive glass installer and repairer',
  },
  {
    label: 'Automotive service mechanic',
    value: 'Automotive service mechanic',
  },
  {
    label: 'Avionics technician',
    value: 'Avionics technician',
  },
  {
    label: 'Baggage Handler',
    value: 'Baggage Handler',
  },
  {
    label: 'Baggage porter, bellhop, and concierge',
    value: 'Baggage porter, bellhop, and concierge',
  },
  {
    label: 'Bail bondsman',
    value: 'Bail bondsman',
  },
  {
    label: 'Bailiff or jailer',
    value: 'Bailiff or jailer',
  },
  {
    label: 'Baker',
    value: 'Baker',
  },
  {
    label: 'Bar Manager, Doorman, or Bouncer',
    value: 'Bar Manager, Doorman, or Bouncer',
  },
  {
    label: 'Barber, hairdresser, hairstylist',
    value: 'Barber, hairdresser, hairstylist',
  },
  {
    label: 'Bartender',
    value: 'Bartender',
  },
  {
    label: 'Bicycle repairer',
    value: 'Bicycle repairer',
  },
  {
    label: 'Bill and account collector',
    value: 'Bill and account collector',
  },
  {
    label: 'BioChemist',
    value: 'BioChemist',
  },
  {
    label: 'Biomedical engineer',
    value: 'Biomedical engineer',
  },
  {
    label: 'BioPhysicist',
    value: 'BioPhysicist',
  },
  {
    label: 'Boilermaker',
    value: 'Boilermaker',
  },
  {
    label: 'Bomb Disposal Crew',
    value: 'Bomb Disposal Crew',
  },
  {
    label: 'Bookkeeper',
    value: 'Bookkeeper',
  },
  {
    label: 'Border Patrol',
    value: 'Border Patrol',
  },
  {
    label: 'Brickmason or Stonemason',
    value: 'Brickmason or Stonemason',
  },
  {
    label: 'Bridge Construction worker',
    value: 'Bridge Construction worker',
  },
  {
    label: 'Building maintenance',
    value: 'Building maintenance',
  },
  {
    label: 'Bus and truck mechanic',
    value: 'Bus and truck mechanic',
  },
  {
    label: 'Bus driver, school or special client',
    value: 'Bus driver, school or special client',
  },
  {
    label: 'Bus driver, transit and intercity',
    value: 'Bus driver, transit and intercity',
  },
  {
    label: 'Business manager',
    value: 'Business manager',
  },
  {
    label: 'Butcher and meat cutter',
    value: 'Butcher and meat cutter',
  },
  {
    label: 'Cabinetmaker and bench carpenter',
    value: 'Cabinetmaker and bench carpenter',
  },
  {
    label: 'Camera equipment repairer',
    value: 'Camera equipment repairer',
  },
  {
    label: 'Camera operator, television or video',
    value: 'Camera operator, television or video',
  },
  {
    label: 'Captain or Crew of water vessel',
    value: 'Captain or Crew of water vessel',
  },
  {
    label: 'Car Wash Worker',
    value: 'Car Wash Worker',
  },
  {
    label: 'Cardiovascular technologist or technician',
    value: 'Cardiovascular technologist or technician',
  },
  {
    label: 'Carpenter',
    value: 'Carpenter',
  },
  {
    label: 'Carpet,tile,floor installer',
    value: 'Carpet,tile,floor installer',
  },
  {
    label: 'Cartographer',
    value: 'Cartographer',
  },
  {
    label: 'Cashier',
    value: 'Cashier',
  },
  {
    label: 'Casino, Gaming booth cashier',
    value: 'Casino, Gaming booth cashier',
  },
  {
    label: 'Casino, Gaming cage worker',
    value: 'Casino, Gaming cage worker',
  },
  {
    label: 'Casino, Gaming Security guard',
    value: 'Casino, Gaming Security guard',
  },
  {
    label: 'Caterer',
    value: 'Caterer',
  },
  {
    label: 'Ceiling tile installer',
    value: 'Ceiling tile installer',
  },
  {
    label: 'Cement mason, concrete worker',
    value: 'Cement mason, concrete worker',
  },
  {
    label: 'Cement or dump truck driver',
    value: 'Cement or dump truck driver',
  },
  {
    label: 'Chef',
    value: 'Chef',
  },
  {
    label: 'Chemical & Biological Weaponary Testing',
    value: 'Chemical & Biological Weaponary Testing',
  },
  {
    label: 'Chemical engineer or technician',
    value: 'Chemical engineer or technician',
  },
  {
    label: 'Chemical equipment operator and tender',
    value: 'Chemical equipment operator and tender',
  },
  {
    label: 'Chemical plant and system operator',
    value: 'Chemical plant and system operator',
  },
  {
    label: 'Chemist',
    value: 'Chemist',
  },
  {
    label: 'Chief executive',
    value: 'Chief executive',
  },
  {
    label: 'Childcare worker',
    value: 'Childcare worker',
  },
  {
    label: 'Chiropractor',
    value: 'Chiropractor',
  },
  {
    label: 'Choreographer',
    value: 'Choreographer',
  },
  {
    label: 'Circus or carnival performer or worker',
    value: 'Circus or carnival performer or worker',
  },
  {
    label: 'Civil engineer or technician',
    value: 'Civil engineer or technician',
  },
  {
    label: 'Claims adjuster, examiner',
    value: 'Claims adjuster, examiner',
  },
  {
    label: 'Clerk',
    value: 'Clerk',
  },
  {
    label: 'Club pro, golf, tennis, swimming, fitness',
    value: 'Club pro, golf, tennis, swimming, fitness',
  },
  {
    label: 'Coach, Umpire, or Related worker',
    value: 'Coach, Umpire, or Related worker',
  },
  {
    label: 'Coal Miner',
    value: 'Coal Miner',
  },
  {
    label: 'Coin or vending machine svc or repair',
    value: 'Coin or vending machine svc or repair',
  },
  {
    label: 'Commercial and industrial designer',
    value: 'Commercial and industrial designer',
  },
  {
    label: 'Commercial Fisherman',
    value: 'Commercial Fisherman',
  },
  {
    label: 'Commercial Mover or Packer',
    value: 'Commercial Mover or Packer',
  },
  {
    label: 'Commercial or marine diver',
    value: 'Commercial or marine diver',
  },
  {
    label: 'Commercial pilot',
    value: 'Commercial pilot',
  },
  {
    label: 'Commodities Broker or Day Trader',
    value: 'Commodities Broker or Day Trader',
  },
  {
    label: 'Communications equipment operator',
    value: 'Communications equipment operator',
  },
  {
    label: 'Community health worker',
    value: 'Community health worker',
  },
  {
    label: 'Compliance officer',
    value: 'Compliance officer',
  },
  {
    label: 'Composer',
    value: 'Composer',
  },
  {
    label: 'Computer control programmer and operator',
    value: 'Computer control programmer and operator',
  },
  {
    label: 'Computer hardware engineer',
    value: 'Computer hardware engineer',
  },
  {
    label: 'Computer programmer',
    value: 'Computer programmer',
  },
  {
    label: 'Computer support specialist',
    value: 'Computer support specialist',
  },
  {
    label: 'Computer, ATM or business maching repair',
    value: 'Computer, ATM or business maching repair',
  },
  {
    label: 'Conservation scientist',
    value: 'Conservation scientist',
  },
  {
    label: 'Construction worker',
    value: 'Construction worker',
  },
  {
    label: 'Construction equipment operator',
    value: 'Construction equipment operator',
  },
  {
    label: 'Construction laborer',
    value: 'Construction laborer',
  },
  {
    label: 'Construction or building inspector',
    value: 'Construction or building inspector',
  },
  {
    label: 'Consultant',
    value: 'Consultant',
  },
  {
    label: 'Control and valve installer and repairer',
    value: 'Control and valve installer and repairer',
  },
  {
    label: 'Convenience Store worker',
    value: 'Convenience Store worker',
  },
  {
    label: 'Cook',
    value: 'Cook',
  },
  {
    label: 'Cook, fast food',
    value: 'Cook, fast food',
  },
  {
    label: 'Cook, private household',
    value: 'Cook, private household',
  },
  {
    label: 'Coroner',
    value: 'Coroner',
  },
  {
    label: 'Correctional officer',
    value: 'Correctional officer',
  },
  {
    label: 'Counselor',
    value: 'Counselor',
  },
  {
    label: 'Countertop worker; laminates or wood',
    value: 'Countertop worker; laminates or wood',
  },
  {
    label: 'Countertop worker; stone or cement',
    value: 'Countertop worker; stone or cement',
  },
  {
    label: 'Court reporter',
    value: 'Court reporter',
  },
  {
    label: 'Credit counselor',
    value: 'Credit counselor',
  },
  {
    label: 'Crossing guards',
    value: 'Crossing guards',
  },
  {
    label: 'Customer service representative',
    value: 'Customer service representative',
  },
  {
    label: 'Cutting worker',
    value: 'Cutting worker',
  },
  {
    label: 'Dancer',
    value: 'Dancer',
  },
  {
    label: 'Data entry',
    value: 'Data entry',
  },
  {
    label: 'Database or Network administrator',
    value: 'Database or Network administrator',
  },
  {
    label: 'Day Care or Pre School in residence',
    value: 'Day Care or Pre School in residence',
  },
  {
    label: 'Day Care or Pre School not in residence',
    value: 'Day Care or Pre School not in residence',
  },
  {
    label: 'Demonstrator and product promoter',
    value: 'Demonstrator and product promoter',
  },
  {
    label: 'Dental assistant',
    value: 'Dental assistant',
  },
  {
    label: 'Dental hygienist',
    value: 'Dental hygienist',
  },
  {
    label: 'Dental laboratory technician',
    value: 'Dental laboratory technician',
  },
  {
    label: 'Dentist',
    value: 'Dentist',
  },
  {
    label: 'Derrick or driller oil, gas, or mining',
    value: 'Derrick or driller oil, gas, or mining',
  },
  {
    label: 'Designer',
    value: 'Designer',
  },
  {
    label: 'Detective and criminal investigator',
    value: 'Detective and criminal investigator',
  },
  {
    label: 'Dietitian or nutritionist',
    value: 'Dietitian or nutritionist',
  },
  {
    label: 'Dishwasher',
    value: 'Dishwasher',
  },
  {
    label: 'Dispatcher',
    value: 'Dispatcher',
  },
  {
    label: 'Dock worker or Longshoreman',
    value: 'Dock worker or Longshoreman',
  },
  {
    label: 'Door-to-door sales, news or street vendor',
    value: 'Door-to-door sales, news or street vendor',
  },
  {
    label: 'Drafter',
    value: 'Drafter',
  },
  {
    label: 'Driver/sales worker',
    value: 'Driver/sales worker',
  },
  {
    label: 'Dry Cleaning Worker',
    value: 'Dry Cleaning Worker',
  },
  {
    label: 'Drywall installer',
    value: 'Drywall installer',
  },
  {
    label: 'Earth driller, except oil and gas',
    value: 'Earth driller, except oil and gas',
  },
  {
    label: 'Economist',
    value: 'Economist',
  },
  {
    label: 'Editor',
    value: 'Editor',
  },
  {
    label: 'Electric motor repairer',
    value: 'Electric motor repairer',
  },
  {
    label: 'Electrical mechanic or repairer',
    value: 'Electrical mechanic or repairer',
  },
  {
    label: 'Electrical or Overhead power-line worker',
    value: 'Electrical or Overhead power-line worker',
  },
  {
    label: 'Electrician',
    value: 'Electrician',
  },
  {
    label: 'Elevator installer and repairer',
    value: 'Elevator installer and repairer',
  },
  {
    label: 'Embalmer',
    value: 'Embalmer',
  },
  {
    label: 'Emergency management director',
    value: 'Emergency management director',
  },
  {
    label: 'Emergency med technician or paramedic',
    value: 'Emergency med technician or paramedic',
  },
  {
    label: 'Engine and other machine assembler',
    value: 'Engine and other machine assembler',
  },
  {
    label: 'Engineer or engineering technician',
    value: 'Engineer or engineering technician',
  },
  {
    label: 'Entertainer or performer',
    value: 'Entertainer or performer',
  },
  {
    label: 'Environmental engineer',
    value: 'Environmental engineer',
  },
  {
    label: 'Environmental scientist or geoscientist',
    value: 'Environmental scientist or geoscientist',
  },
  {
    label: 'Epidemiologist',
    value: 'Epidemiologist',
  },
  {
    label: 'Equipment assembler',
    value: 'Equipment assembler',
  },
  {
    label: 'Etcher and engraver',
    value: 'Etcher and engraver',
  },
  {
    label: 'Event planner',
    value: 'Event planner',
  },
  {
    label: 'Exercise physiologist',
    value: 'Exercise physiologist',
  },
  {
    label: 'Explosives blaster or handler',
    value: 'Explosives blaster or handler',
  },
  {
    label: 'Extraction worker',
    value: 'Extraction worker',
  },
  {
    label: 'Fabric and apparel patternmaker',
    value: 'Fabric and apparel patternmaker',
  },
  {
    label: 'Fabric mender, except garment',
    value: 'Fabric mender, except garment',
  },
  {
    label: 'Factory worker',
    value: 'Factory worker',
  },
  {
    label: 'Farm equipment mechanic or technician',
    value: 'Farm equipment mechanic or technician',
  },
  {
    label: 'Farm Labor',
    value: 'Farm Labor',
  },
  {
    label: 'Farm or ranch worker, unskilled',
    value: 'Farm or ranch worker, unskilled',
  },
  {
    label: 'Farmer',
    value: 'Farmer',
  },
  {
    label: 'Fashion designer',
    value: 'Fashion designer',
  },
  {
    label: 'Fast food worker or busboy',
    value: 'Fast food worker or busboy',
  },
  {
    label: 'Fence erector',
    value: 'Fence erector',
  },
  {
    label: 'Fiberglass laminator and fabricator',
    value: 'Fiberglass laminator and fabricator',
  },
  {
    label: 'Film and video editor',
    value: 'Film and video editor',
  },
  {
    label: 'Financial analyst',
    value: 'Financial analyst',
  },
  {
    label: 'Financial Service Agent',
    value: 'Financial Service Agent',
  },
  {
    label: 'Fire inspector',
    value: 'Fire inspector',
  },
  {
    label: 'Firefighter',
    value: 'Firefighter',
  },
  {
    label: 'Fitness or Personal Trainer',
    value: 'Fitness or Personal Trainer',
  },
  {
    label: 'Flagpole or steeplejack workers',
    value: 'Flagpole or steeplejack workers',
  },
  {
    label: 'Flight attendant',
    value: 'Flight attendant',
  },
  {
    label: 'Flight engineer',
    value: 'Flight engineer',
  },
  {
    label: 'Floor sander and finisher',
    value: 'Floor sander and finisher',
  },
  {
    label: 'Floral designer or florist',
    value: 'Floral designer or florist',
  },
  {
    label: 'Food or beverage server',
    value: 'Food or beverage server',
  },
  {
    label: 'Food preparation worker',
    value: 'Food preparation worker',
  },
  {
    label: 'Food scientist and technologist',
    value: 'Food scientist and technologist',
  },
  {
    label: 'Foreman',
    value: 'Foreman',
  },
  {
    label: 'Forensic science technician',
    value: 'Forensic science technician',
  },
  {
    label: 'Forest ranger or conservation worker',
    value: 'Forest ranger or conservation worker',
  },
  {
    label: 'Forester or forest technician',
    value: 'Forester or forest technician',
  },
  {
    label: 'Forklift Driver',
    value: 'Forklift Driver',
  },
  {
    label: 'Foundry mold and coremaker',
    value: 'Foundry mold and coremaker',
  },
  {
    label: 'Fundraiser',
    value: 'Fundraiser',
  },
  {
    label: 'Funeral service worker',
    value: 'Funeral service worker',
  },
  {
    label: 'Furnace, kiln operator',
    value: 'Furnace, kiln operator',
  },
  {
    label: 'Furniture finisher',
    value: 'Furniture finisher',
  },
  {
    label: 'Garbage Route Worker',
    value: 'Garbage Route Worker',
  },
  {
    label: 'Garbage Truck Driver',
    value: 'Garbage Truck Driver',
  },
  {
    label: 'Gas compressor or gas pumper',
    value: 'Gas compressor or gas pumper',
  },
  {
    label: 'Gas plant operator',
    value: 'Gas plant operator',
  },
  {
    label: 'Genetic Counselor',
    value: 'Genetic Counselor',
  },
  {
    label: 'Geographer',
    value: 'Geographer',
  },
  {
    label: 'Geological and petroleum technician',
    value: 'Geological and petroleum technician',
  },
  {
    label: 'Geologist',
    value: 'Geologist',
  },
  {
    label: 'Glass Installer or Glazier, Commercial',
    value: 'Glass Installer or Glazier, Commercial',
  },
  {
    label: 'Glass Installer or Glazier, Residential',
    value: 'Glass Installer or Glazier, Residential',
  },
  {
    label: 'Graphic designer',
    value: 'Graphic designer',
  },
  {
    label: 'Grounds maintenance worker',
    value: 'Grounds maintenance worker',
  },
  {
    label: 'Groundskeeping worker',
    value: 'Groundskeeping worker',
  },
  {
    label: 'Health and safety engineer',
    value: 'Health and safety engineer',
  },
  {
    label: 'Hearing aid specialist',
    value: 'Hearing aid specialist',
  },
  {
    label: 'Heating, air conditioning, (HVAC) worker',
    value: 'Heating, air conditioning, (HVAC) worker',
  },
  {
    label: 'Heavy Equipment Operator',
    value: 'Heavy Equipment Operator',
  },
  {
    label: 'Heavy vehicle or equipment service',
    value: 'Heavy vehicle or equipment service',
  },
  {
    label: 'Helper, construction trades',
    value: 'Helper, construction trades',
  },
  {
    label: 'Highway maintenance worker or flagman',
    value: 'Highway maintenance worker or flagman',
  },
  {
    label: 'Historian',
    value: 'Historian',
  },
  {
    label: 'Hoist and winch operator',
    value: 'Hoist and winch operator',
  },
  {
    label: 'Home appliance repairer',
    value: 'Home appliance repairer',
  },
  {
    label: 'Home entertainment installer and repairer',
    value: 'Home entertainment installer and repairer',
  },
  {
    label: 'Home health care provider or aide',
    value: 'Home health care provider or aide',
  },
  {
    label: 'Human resources worker',
    value: 'Human resources worker',
  },
  {
    label: 'Humane Shelter worker',
    value: 'Humane Shelter worker',
  },
  {
    label: 'Industrial engineer and technician',
    value: 'Industrial engineer and technician',
  },
  {
    label: 'Industrial machinery mechanic',
    value: 'Industrial machinery mechanic',
  },
  {
    label: 'Information Technologist',
    value: 'Information Technologist',
  },
  {
    label: 'Inspector, Tester',
    value: 'Inspector, Tester',
  },
  {
    label: 'Insulation worker',
    value: 'Insulation worker',
  },
  {
    label: 'Insurance Sales Agent',
    value: 'Insurance Sales Agent',
  },
  {
    label: 'Insurance underwriter',
    value: 'Insurance underwriter',
  },
  {
    label: 'Interior designer',
    value: 'Interior designer',
  },
  {
    label: 'Interpreter or translator',
    value: 'Interpreter or translator',
  },
  {
    label: 'Ironworker',
    value: 'Ironworker',
  },
  {
    label: 'Janitor or cleaner',
    value: 'Janitor or cleaner',
  },
  {
    label: 'Jeweler and precious stone worker',
    value: 'Jeweler and precious stone worker',
  },
  {
    label: 'Judge, magistrate judge or adjudicator',
    value: 'Judge, magistrate judge or adjudicator',
  },
  {
    label: 'Judicial law clerk',
    value: 'Judicial law clerk',
  },
  {
    label: 'Junk dealer',
    value: 'Junk dealer',
  },
  {
    label: 'Lab Technician',
    value: 'Lab Technician',
  },
  {
    label: 'Landscaper',
    value: 'Landscaper',
  },
  {
    label: 'Laundry or Laundromat worker',
    value: 'Laundry or Laundromat worker',
  },
  {
    label: 'Law enforcement Office worker',
    value: 'Law enforcement Office worker',
  },
  {
    label: 'Lawyer or Attorney',
    value: 'Lawyer or Attorney',
  },
  {
    label: 'Legislator or elected official',
    value: 'Legislator or elected official',
  },
  {
    label: 'Librarian',
    value: 'Librarian',
  },
  {
    label: 'Library technician',
    value: 'Library technician',
  },
  {
    label: 'Licensed practical nurse (LPN)',
    value: 'Licensed practical nurse (LPN)',
  },
  {
    label: 'Licensed vocational nurse (LVN)',
    value: 'Licensed vocational nurse (LVN)',
  },
  {
    label: 'Lifeguard, ski patrol, or other',
    value: 'Lifeguard, ski patrol, or other',
  },
  {
    label: 'Loan officer',
    value: 'Loan officer',
  },
  {
    label: 'Locker,coat or dressing room attendant',
    value: 'Locker,coat or dressing room attendant',
  },
  {
    label: 'Locksmith and safe repairer',
    value: 'Locksmith and safe repairer',
  },
  {
    label: 'Locomotive engineer and operator',
    value: 'Locomotive engineer and operator',
  },
  {
    label: 'Logging equipment operator',
    value: 'Logging equipment operator',
  },
  {
    label: 'Logging hauler or worker',
    value: 'Logging hauler or worker',
  },
  {
    label: 'Machine tool setter, operator',
    value: 'Machine tool setter, operator',
  },
  {
    label: 'Machinist',
    value: 'Machinist',
  },
  {
    label: 'Maid, housekeeper, cleaner',
    value: 'Maid, housekeeper, cleaner',
  },
  {
    label: 'Maintenance worker, machinery',
    value: 'Maintenance worker, machinery',
  },
  {
    label: 'Makeup artist, theatrical and performance',
    value: 'Makeup artist, theatrical and performance',
  },
  {
    label: 'Manager',
    value: 'Manager',
  },
  {
    label: 'Manicurist and pedicurist',
    value: 'Manicurist and pedicurist',
  },
  {
    label: 'Manufactured or mobile bldg installer',
    value: 'Manufactured or mobile bldg installer',
  },
  {
    label: 'Marine engineer and naval architect',
    value: 'Marine engineer and naval architect',
  },
  {
    label: 'Masseusse (Spa)',
    value: 'Masseusse (Spa)',
  },
  {
    label: 'Meat, poultry, and fish trimmer',
    value: 'Meat, poultry, and fish trimmer',
  },
  {
    label: 'Mechanical door repairer',
    value: 'Mechanical door repairer',
  },
  {
    label: 'Mechanical engineer or technician',
    value: 'Mechanical engineer or technician',
  },
  {
    label: 'Media and communication worker',
    value: 'Media and communication worker',
  },
  {
    label: 'Medical appliance technician',
    value: 'Medical appliance technician',
  },
  {
    label: 'Medical assistant',
    value: 'Medical assistant',
  },
  {
    label: 'Medical equipment preparer',
    value: 'Medical equipment preparer',
  },
  {
    label: 'Medical equipment repairer',
    value: 'Medical equipment repairer',
  },
  {
    label: 'Medical Massage therapist (Not Spa)',
    value: 'Medical Massage therapist (Not Spa)',
  },
  {
    label: 'Medical records technician',
    value: 'Medical records technician',
  },
  {
    label: 'Medical scientist',
    value: 'Medical scientist',
  },
  {
    label: 'Medical transcriptionist',
    value: 'Medical transcriptionist',
  },
  {
    label: 'Medical, dental, laboratory technician',
    value: 'Medical, dental, laboratory technician',
  },
  {
    label: 'Metal furnace operator',
    value: 'Metal furnace operator',
  },
  {
    label: 'Meter reader, utilities',
    value: 'Meter reader, utilities',
  },
  {
    label: 'Microbiologist',
    value: 'Microbiologist',
  },
  {
    label: 'Midwife',
    value: 'Midwife',
  },
  {
    label: 'Migrant Worker',
    value: 'Migrant Worker',
  },
  {
    label: 'Military',
    value: 'Military',
  },
  {
    label: 'Milling and planing machine operator',
    value: 'Milling and planing machine operator',
  },
  {
    label: 'Millwright',
    value: 'Millwright',
  },
  {
    label: 'Mining engineer mining safety engineer',
    value: 'Mining engineer mining safety engineer',
  },
  {
    label: 'Mining machine operator',
    value: 'Mining machine operator',
  },
  {
    label: 'Mining roof bolter',
    value: 'Mining roof bolter',
  },
  {
    label: 'Minister, Preacher, or Priest',
    value: 'Minister, Preacher, or Priest',
  },
  {
    label: 'Miscellaneous sales and related worker',
    value: 'Miscellaneous sales and related worker',
  },
  {
    label: 'Missionary',
    value: 'Missionary',
  },
  {
    label: 'Mobile heavy equipment mechanic',
    value: 'Mobile heavy equipment mechanic',
  },
  {
    label: 'Model',
    value: 'Model',
  },
  {
    label: 'Mortician, undertaker or funeral director',
    value: 'Mortician, undertaker or funeral director',
  },
  {
    label: 'Motorboat mechanic and service technician',
    value: 'Motorboat mechanic and service technician',
  },
  {
    label: 'Motorboat operator',
    value: 'Motorboat operator',
  },
  {
    label: 'Motorcycle mechanic',
    value: 'Motorcycle mechanic',
  },
  {
    label: 'MRI or XrayTechnician',
    value: 'MRI or XrayTechnician',
  },
  {
    label: 'Music director',
    value: 'Music director',
  },
  {
    label: 'Musical instrument repairer and tuner',
    value: 'Musical instrument repairer and tuner',
  },
  {
    label: 'Musician or singer',
    value: 'Musician or singer',
  },
  {
    label: 'Nanny',
    value: 'Nanny',
  },
  {
    label: 'News analyst',
    value: 'News analyst',
  },
  {
    label: 'Nuclear engineer or technician',
    value: 'Nuclear engineer or technician',
  },
  {
    label: 'Nuclear medicine technologist',
    value: 'Nuclear medicine technologist',
  },
  {
    label: 'Nuclear power reactor operator or worker',
    value: 'Nuclear power reactor operator or worker',
  },
  {
    label: 'Nurse anesthetist',
    value: 'Nurse anesthetist',
  },
  {
    label: 'Nurse practitioner',
    value: 'Nurse practitioner',
  },
  {
    label: 'Nursery or greenhouse worker',
    value: 'Nursery or greenhouse worker',
  },
  {
    label: 'Nursing assistant',
    value: 'Nursing assistant',
  },
  {
    label: 'Nursing, psychiatric',
    value: 'Nursing, psychiatric',
  },
  {
    label: 'Occupational therapist',
    value: 'Occupational therapist',
  },
  {
    label: 'Office and administrative support worker',
    value: 'Office and administrative support worker',
  },
  {
    label: 'Office machine operator, except computer',
    value: 'Office machine operator, except computer',
  },
  {
    label: 'Offshore Worker',
    value: 'Offshore Worker',
  },
  {
    label: 'Oil, Gas, or Mining occupation',
    value: 'Oil, Gas, or Mining occupation',
  },
  {
    label: 'Ophthalmic laboratory technician',
    value: 'Ophthalmic laboratory technician',
  },
  {
    label: 'Ophthalmic medical technician',
    value: 'Ophthalmic medical technician',
  },
  {
    label: 'Optician, dispensing',
    value: 'Optician, dispensing',
  },
  {
    label: 'Optometrist',
    value: 'Optometrist',
  },
  {
    label: 'Oral and maxillofacial surgeon',
    value: 'Oral and maxillofacial surgeon',
  },
  {
    label: 'Orderly',
    value: 'Orderly',
  },
  {
    label: 'Orthodontist',
    value: 'Orthodontist',
  },
  {
    label: 'Orthotist or prosthetist',
    value: 'Orthotist or prosthetist',
  },
  {
    label: 'Information security analyst',
    value: 'Information security analyst',
  },
  {
    label: 'Outdoor power mechanic',
    value: 'Outdoor power mechanic',
  },
  {
    label: 'Packer and packager, hand',
    value: 'Packer and packager, hand',
  },
  {
    label: 'Painter, construction and maintenance',
    value: 'Painter, construction and maintenance',
  },
  {
    label: 'Painter, residential',
    value: 'Painter, residential',
  },
  {
    label: 'Painting, coating, and decorating worker',
    value: 'Painting, coating, and decorating worker',
  },
  {
    label: 'Paralegal or legal assistant',
    value: 'Paralegal or legal assistant',
  },
  {
    label: 'Parking enforcement worker',
    value: 'Parking enforcement worker',
  },
  {
    label: 'Parking lot attendant',
    value: 'Parking lot attendant',
  },
  {
    label: 'Patternmaker, metal and plastic',
    value: 'Patternmaker, metal and plastic',
  },
  {
    label: 'Patternmaker, wood',
    value: 'Patternmaker, wood',
  },
  {
    label: 'Pawnbroker',
    value: 'Pawnbroker',
  },
  {
    label: 'Pest control worker',
    value: 'Pest control worker',
  },
  {
    label: 'Pharmacist',
    value: 'Pharmacist',
  },
  {
    label: 'Pharmacy technician',
    value: 'Pharmacy technician',
  },
  {
    label: 'Phlebotomist',
    value: 'Phlebotomist',
  },
  {
    label: 'Photographer or Portrait Photographer',
    value: 'Photographer or Portrait Photographer',
  },
  {
    label: 'Photographic process worker',
    value: 'Photographic process worker',
  },
  {
    label: 'Physical therapist',
    value: 'Physical therapist',
  },
  {
    label: 'Physician assistant',
    value: 'Physician assistant',
  },
  {
    label: 'Physician or Doctor',
    value: 'Physician or Doctor',
  },
  {
    label: 'Physicist',
    value: 'Physicist',
  },
  {
    label: 'Pile-driver operator',
    value: 'Pile-driver operator',
  },
  {
    label: 'Plasterer or stucco mason',
    value: 'Plasterer or stucco mason',
  },
  {
    label: 'Plumber, Pipefitter, and Steamfitter',
    value: 'Plumber, Pipefitter, and Steamfitter',
  },
  {
    label: 'Podiatrist',
    value: 'Podiatrist',
  },
  {
    label: 'Police officer',
    value: 'Police officer',
  },
  {
    label: 'Postal service mail carrier',
    value: 'Postal service mail carrier',
  },
  {
    label: 'Postal service office worker',
    value: 'Postal service office worker',
  },
  {
    label: 'Postmaster and mail superintendent',
    value: 'Postmaster and mail superintendent',
  },
  {
    label: 'Power plant operator or worker',
    value: 'Power plant operator or worker',
  },
  {
    label: 'Precision instrument repairer',
    value: 'Precision instrument repairer',
  },
  {
    label: 'Printing press operator or worker',
    value: 'Printing press operator or worker',
  },
  {
    label: 'Prison Guard',
    value: 'Prison Guard',
  },
  {
    label: 'Private detective and investigator',
    value: 'Private detective and investigator',
  },
  {
    label: 'Probation officer',
    value: 'Probation officer',
  },
  {
    label: 'Producer or director',
    value: 'Producer or director',
  },
  {
    label: 'Production worker',
    value: 'Production worker',
  },
  {
    label: 'Professor',
    value: 'Professor',
  },
  {
    label: 'Prosthodontist',
    value: 'Prosthodontist',
  },
  {
    label: 'Psychiatric aide',
    value: 'Psychiatric aide',
  },
  {
    label: 'Psychiatric technician',
    value: 'Psychiatric technician',
  },
  {
    label: 'Psychiatrist',
    value: 'Psychiatrist',
  },
  {
    label: 'Psychologist',
    value: 'Psychologist',
  },
  {
    label: 'Public Announcer',
    value: 'Public Announcer',
  },
  {
    label: 'Public relations specialist',
    value: 'Public relations specialist',
  },
  {
    label: 'Pumping station operator',
    value: 'Pumping station operator',
  },
  {
    label: 'Purchasing Agent',
    value: 'Purchasing Agent',
  },
  {
    label: 'Radiation therapist',
    value: 'Radiation therapist',
  },
  {
    label: 'Radio and communications installer',
    value: 'Radio and communications installer',
  },
  {
    label: 'Radio operator',
    value: 'Radio operator',
  },
  {
    label: 'Radio or television announcer',
    value: 'Radio or television announcer',
  },
  {
    label: 'Radio, cellular, and tower equipment',
    value: 'Radio, cellular, and tower equipment',
  },
  {
    label: 'Rail car repairer',
    value: 'Rail car repairer',
  },
  {
    label: 'Railroad conductor and yardmaster',
    value: 'Railroad conductor and yardmaster',
  },
  {
    label: 'Railroad Worker',
    value: 'Railroad Worker',
  },
  {
    label: 'Rail-track layer or maintenance opr',
    value: 'Rail-track layer or maintenance opr',
  },
  {
    label: 'Real estate broker and Agent',
    value: 'Real estate broker and Agent',
  },
  {
    label: 'Receptionist',
    value: 'Receptionist',
  },
  {
    label: 'Recreation and fitness worker',
    value: 'Recreation and fitness worker',
  },
  {
    label: 'Recreational vehicle service technician',
    value: 'Recreational vehicle service technician',
  },
  {
    label: 'Registered nurse',
    value: 'Registered nurse',
  },
  {
    label: 'Rehabilitation Counselor',
    value: 'Rehabilitation Counselor',
  },
  {
    label: 'Reinforcing iron and rebar worker',
    value: 'Reinforcing iron and rebar worker',
  },
  {
    label: 'Religious worker',
    value: 'Religious worker',
  },
  {
    label: 'Rendering Plant Worker',
    value: 'Rendering Plant Worker',
  },
  {
    label: 'Reporter, journalist, or correspondent',
    value: 'Reporter, journalist, or correspondent',
  },
  {
    label: 'Respiratory therapist',
    value: 'Respiratory therapist',
  },
  {
    label: 'Retail sales worker',
    value: 'Retail sales worker',
  },
  {
    label: 'Rigger',
    value: 'Rigger',
  },
  {
    label: 'Rock splitter, quarry',
    value: 'Rock splitter, quarry',
  },
  {
    label: 'Roofer',
    value: 'Roofer',
  },
  {
    label: 'Roustabout, oil and gas',
    value: 'Roustabout, oil and gas',
  },
  {
    label: 'Sales representative, service, all other',
    value: 'Sales representative, service, all other',
  },
  {
    label: 'Scuba or Snorkle Instructor',
    value: 'Scuba or Snorkle Instructor',
  },
  {
    label: 'Secretary or administrative assistant',
    value: 'Secretary or administrative assistant',
  },
  {
    label: 'Security and fire alarm systems installer',
    value: 'Security and fire alarm systems installer',
  },
  {
    label: 'Security guard',
    value: 'Security guard',
  },
  {
    label: 'Septic tank svc or sewer pipe cleaner',
    value: 'Septic tank svc or sewer pipe cleaner',
  },
  {
    label: 'Set and exhibit designer',
    value: 'Set and exhibit designer',
  },
  {
    label: 'Sewing machine operator',
    value: 'Sewing machine operator',
  },
  {
    label: 'Sheet metal worker',
    value: 'Sheet metal worker',
  },
  {
    label: 'Ship and boat captain and operator',
    value: 'Ship and boat captain and operator',
  },
  {
    label: 'Shoe and leather repair or worker',
    value: 'Shoe and leather repair or worker',
  },
  {
    label: 'Signal and track switch repairer',
    value: 'Signal and track switch repairer',
  },
  {
    label: 'Slaughterer and meat packer',
    value: 'Slaughterer and meat packer',
  },
  {
    label: 'Small engine mechanic',
    value: 'Small engine mechanic',
  },
  {
    label: 'Social worker',
    value: 'Social worker',
  },
  {
    label: 'Sociologist',
    value: 'Sociologist',
  },
  {
    label: 'Software developer and programmer',
    value: 'Software developer and programmer',
  },
  {
    label: 'Solar panel installer',
    value: 'Solar panel installer',
  },
  {
    label: 'Sonographer',
    value: 'Sonographer',
  },
  {
    label: 'Sound engineering technician',
    value: 'Sound engineering technician',
  },
  {
    label: 'Speech-language pathologist',
    value: 'Speech-language pathologist',
  },
  {
    label: 'Sports Scout',
    value: 'Sports Scout',
  },
  {
    label: 'Sprinkler installer',
    value: 'Sprinkler installer',
  },
  {
    label: 'Statistician',
    value: 'Statistician',
  },
  {
    label: 'Stockbroker',
    value: 'Stockbroker',
  },
  {
    label: 'Structural iron and steel worker',
    value: 'Structural iron and steel worker',
  },
  {
    label: 'Substance abuse or Behavior Counselor',
    value: 'Substance abuse or Behavior Counselor',
  },
  {
    label: 'Substitute teacher',
    value: 'Substitute teacher',
  },
  {
    label: 'Subway and streetcar opr or conductor',
    value: 'Subway and streetcar opr or conductor',
  },
  {
    label: 'Surgeon',
    value: 'Surgeon',
  },
  {
    label: 'Surveyor',
    value: 'Surveyor',
  },
  {
    label: 'Switchboard operator',
    value: 'Switchboard operator',
  },
  {
    label: 'Systems analyst',
    value: 'Systems analyst',
  },
  {
    label: 'Tailor, dressmaker, or Seamstress',
    value: 'Tailor, dressmaker, or Seamstress',
  },
  {
    label: 'Tank, car, truck, and ship loader',
    value: 'Tank, car, truck, and ship loader',
  },
  {
    label: 'Taper',
    value: 'Taper',
  },
  {
    label: 'Tax examiner',
    value: 'Tax examiner',
  },
  {
    label: 'Tax preparer',
    value: 'Tax preparer',
  },
  {
    label: 'Taxi driver or chauffeur',
    value: 'Taxi driver or chauffeur',
  },
  {
    label: 'Teacher assistant',
    value: 'Teacher assistant',
  },
  {
    label: 'Teacher or instructor',
    value: 'Teacher or instructor',
  },
  {
    label: 'Technical Writer',
    value: 'Technical Writer',
  },
  {
    label: 'Telemarketer',
    value: 'Telemarketer',
  },
  {
    label: 'Telephone operator',
    value: 'Telephone operator',
  },
  {
    label: 'Teller or Bank worker',
    value: 'Teller or Bank worker',
  },
  {
    label: 'Textile, apparel',
    value: 'Textile, apparel',
  },
  {
    label: 'Therapist',
    value: 'Therapist',
  },
  {
    label: 'Tire repairer and changer',
    value: 'Tire repairer and changer',
  },
  {
    label: 'Title examiner, abstractor, and searcher',
    value: 'Title examiner, abstractor, and searcher',
  },
  {
    label: 'Tobacco machine operator and tender',
    value: 'Tobacco machine operator and tender',
  },
  {
    label: 'Toll Collector',
    value: 'Toll Collector',
  },
  {
    label: 'Tool and die maker',
    value: 'Tool and die maker',
  },
  {
    label: 'Tool grinder, filer, and sharpener',
    value: 'Tool grinder, filer, and sharpener',
  },
  {
    label: 'Tour and travel guide',
    value: 'Tour and travel guide',
  },
  {
    label: 'Tow Truck Driver',
    value: 'Tow Truck Driver',
  },
  {
    label: 'Transit and railroad police',
    value: 'Transit and railroad police',
  },
  {
    label: 'Transportation security worker (TSA)',
    value: 'Transportation security worker (TSA)',
  },
  {
    label: 'Travel Agent',
    value: 'Travel Agent',
  },
  {
    label: 'Tree trimmers and pruner',
    value: 'Tree trimmers and pruner',
  },
  {
    label: 'Truck Driver, Local, Beverage Delivery',
    value: 'Truck Driver, Local, Beverage Delivery',
  },
  {
    label: 'Truck Driver, Local, Light Delivery',
    value: 'Truck Driver, Local, Light Delivery',
  },
  {
    label: 'Truck Driver, Long Haul Over the Road',
    value: 'Truck Driver, Long Haul Over the Road',
  },
  {
    label: 'Underground Construction Worker',
    value: 'Underground Construction Worker',
  },
  {
    label: 'Unskilled Health Care Aide',
    value: 'Unskilled Health Care Aide',
  },
  {
    label: 'Upholsterer',
    value: 'Upholsterer',
  },
  {
    label: 'Urban and regional planner',
    value: 'Urban and regional planner',
  },
  {
    label: 'Usher, lobby attendant, and ticket taker',
    value: 'Usher, lobby attendant, and ticket taker',
  },
  {
    label: 'USPS, UPS, FedEx, Delivery Driver',
    value: 'USPS, UPS, FedEx, Delivery Driver',
  },
  {
    label: 'Valet',
    value: 'Valet',
  },
  {
    label: 'Veterinarian - Large Animal or Mixed',
    value: 'Veterinarian - Large Animal or Mixed',
  },
  {
    label: 'Veterinarian - Small Animal',
    value: 'Veterinarian - Small Animal',
  },
  {
    label: 'Veterinary assistant',
    value: 'Veterinary assistant',
  },
  {
    label: 'Waiter or waitress',
    value: 'Waiter or waitress',
  },
  {
    label: 'Warden, Fish and Game',
    value: 'Warden, Fish and Game',
  },
  {
    label: 'Warden, Prison',
    value: 'Warden, Prison',
  },
  {
    label: 'Warehouse worker',
    value: 'Warehouse worker',
  },
  {
    label: 'Waste Management Route Worker',
    value: 'Waste Management Route Worker',
  },
  {
    label: 'Waste Management Truck Driver',
    value: 'Waste Management Truck Driver',
  },
  {
    label: 'Watch repairer',
    value: 'Watch repairer',
  },
  {
    label: 'Water or wastewater treatment worker',
    value: 'Water or wastewater treatment worker',
  },
  {
    label: 'Web developer',
    value: 'Web developer',
  },
  {
    label: 'Welder, cutter, solderer, and brazer',
    value: 'Welder, cutter, solderer, and brazer',
  },
  {
    label: 'Wellhead pumper',
    value: 'Wellhead pumper',
  },
  {
    label: 'Wild Animal Trainer',
    value: 'Wild Animal Trainer',
  },
  {
    label: 'Wind turbine service technician',
    value: 'Wind turbine service technician',
  },
  {
    label: 'Window washer, Commercial',
    value: 'Window washer, Commercial',
  },
  {
    label: 'Window washer, Residential',
    value: 'Window washer, Residential',
  },
  {
    label: 'Woodworker',
    value: 'Woodworker',
  },
  {
    label: 'Zoologist and wildlife biologist',
    value: 'Zoologist and wildlife biologist',
  },
  {
    label: 'Advertising worker',
    value: 'Advertising worker',
  },
  {
    label: 'Business Agent',
    value: 'Business Agent',
  },
  {
    label: 'Cafe Worker',
    value: 'Cafe Worker',
  },
  {
    label: 'Dance Instructor',
    value: 'Dance Instructor',
  },
  {
    label: 'Entertainment Industry worker',
    value: 'Entertainment Industry worker',
  },
  {
    label: 'Dog Groomer',
    value: 'Dog Groomer',
  },
  {
    label: 'Freight Handler',
    value: 'Freight Handler',
  },
  {
    label: 'Golf Course worker',
    value: 'Golf Course worker',
  },
  {
    label: 'Government Employee',
    value: 'Government Employee',
  },
  {
    label: 'Grocery Store worker',
    value: 'Grocery Store worker',
  },
  {
    label: 'Nursing Home worker',
    value: 'Nursing Home worker',
  },
  {
    label: 'Jockey',
    value: 'Jockey',
  },
  {
    label: 'Laborer, unskilled',
    value: 'Laborer, unskilled',
  },
  {
    label: 'Lecturer',
    value: 'Lecturer',
  },
  {
    label: 'Lumber yard worker',
    value: 'Lumber yard worker',
  },
  {
    label: 'Manufacturing worker',
    value: 'Manufacturing worker',
  },
  {
    label: 'Repairer',
    value: 'Repairer',
  },
  {
    label: 'Restaurant manager',
    value: 'Restaurant manager',
  },
  {
    label: 'Route Driver',
    value: 'Route Driver',
  },
  {
    label: 'Siding Installer',
    value: 'Siding Installer',
  },
  {
    label: 'Animal Care',
    value: 'Animal Care',
  },
  {
    label: 'Stocker',
    value: 'Stocker',
  },
  {
    label: 'Street Cleaner',
    value: 'Street Cleaner',
  },
  {
    label: 'Wallpaperer',
    value: 'Wallpaperer',
  },
  {
    label: 'Zoo Employee',
    value: 'Zoo Employee',
  },
  {
    label: 'Office worker',
    value: 'Office worker',
  },
  {
    label: 'Auctioneer',
    value: 'Auctioneer',
  },
  {
    label: 'Air Hammer Operator',
    value: 'Air Hammer Operator',
  },
];

export const banks: OptionTypes[] = [
  {
    label: 'Bank Of America',
    value: 'Bank Of America',
  },
  {
    label: 'Chase',
    value: 'Chase',
  },
  {
    label: 'Wells Fargo',
    value: 'Wells Fargo',
  },
  {
    label: 'Citi',
    value: 'Citi',
  },
  {
    label: 'U.S. Bank',
    value: 'U.S. Bank',
  },
  {
    label: 'GO2Bank',
    value: 'GO2Bank',
  },
  {
    label: 'Heritage Bank',
    value: 'Heritage Bank',
  },
  {
    label: 'Navy Federal Credit Union',
    value: 'Navy Federal Credit Union',
  },
  {
    label: 'TIAA',
    value: 'TIAA',
  },
  {
    label: 'Goldman Sachs',
    value: 'Goldman Sachs',
  },
  {
    label: 'Morgan Stanley',
    value: 'Morgan Stanley',
  },
  {
    label: 'PNC Bank',
    value: 'PNC Bank',
  },
  {
    label: 'Capital One',
    value: 'Capital One',
  },
  {
    label: 'BB&T and SunTrust (Truist)',
    value: 'BB&T and SunTrust (Truist)',
  },
  {
    label: 'TD Bank',
    value: 'TD Bank',
  },
  {
    label: 'Ally Bank',
    value: 'Ally Bank',
  },
  {
    label: 'HSBC',
    value: 'HSBC',
  },
  {
    label: 'Fifth Third Bank',
    value: 'Fifth Third Bank',
  },
  {
    label: 'KeyBank',
    value: 'KeyBank',
  },
  {
    label: 'Regions Bank',
    value: 'Regions Bank',
  },
  {
    label: 'Santander Bank',
    value: 'Santander Bank',
  },
  {
    label: 'M&T Bank',
    value: 'M&T Bank',
  },
  {
    label: 'Huntington',
    value: 'Huntington',
  },
  {
    label: 'BBVA USA',
    value: 'BBVA USA',
  },
  {
    label: 'Comerica Bank',
    value: 'Comerica Bank',
  },
  {
    label: 'Zions Bank',
    value: 'Zions Bank',
  },
  {
    label: 'Synovus Bank',
    value: 'Synovus Bank',
  },
];

export const routingNumbers: BankRoutingNumbers = {
  'Bank Of America': {
    alabama: '051000017',
    alaska: '051000017',
    arizona: '122101706',
    arkansas: '082000073',
    california: '121000358',
    colorado: '123103716',
    connecticut: '011900254',
    district_of_columbia: '054001204',
    delaware: '031202084',
    florida: '063100277',
    georgia: '061000052',
    hawaii: '051000017',
    idaho: '123103716',
    illinois_south: '081904808',
    illinois_north: '071000505',
    indiana: '071214579',
    iowa: '073000176',
    kansas: '101100045',
    kentucky: '064000020',
    louisiana: '051000017',
    maine: '011200365',
    maryland: '052001633',
    massachusetts: '011000138',
    michigan: '072000805',
    minnesota: '071214579',
    mississippi: '051000017',
    missouri: '081000032',
    montana: '051000017',
    nebraska: '123103716',
    nevada: '122400724',
    new_hampshire: '011400495',
    new_jersey: '021200339',
    new_mexico: '107000327',
    new_york: '021000322',
    north_carolina: '053000196',
    north_dakota: '051000017',
    ohio: '071214579',
    oklahoma: '103000017',
    oregon: '323070380',
    pennsylvania: '031202084',
    rhode_island: '011500010',
    south_carolina: '053904483',
    south_dakota: '051000017',
    tennessee: '064000020',
    texas: '111000025',
    utah: '123103716',
    vermont: '051000017',
    virginia: '051000017',
    washington: '125000024',
    west_virginia: '051000017',
    wisconsin: '123103716',
    wyoming: '051000017',
  },
  Chase: {
    alabama: '065400137',
    arizona: '122100024',
    arkansas: '065400137',
    california: '322271627',
    colorado: '102001017',
    connecticut: '021100361',
    district_of_columbia: '044000037',
    delaware: '083000137',
    florida: '267084131',
    georgia: '061092387',
    idaho: '123271978',
    illinois: '071000013',
    indiana: '074000010',
    iowa: '075000019',
    kansas: '103000648',
    kentucky: '083000137',
    louisiana: '065400137',
    massachusetts: '021000021',
    maryland: '044000037',
    maine: '083000137',
    michigan: '072000326',
    minnesota: '075000019',
    missouri: '103000648',
    mississippi: '065400137',
    montana: '102001017',
    nevada: '322271627',
    new_jersey: '021202337',
    new_york_downstate: '021000021',
    new_york_upstate: '022300173',
    nebraska: '103000648',
    new_hampshire: '083000137',
    new_mexico: '102001017',
    north_carolina: '072000326',
    north_dakota: '103000648',
    ohio: '044000037',
    oklahoma: '103000648',
    oregon: '325070760',
    pennsylvania: '083000137',
    rhode_island: '083000137',
    south_carolina: '072000326',
    south_dakota: '103000648',
    texas: '111000614',
    tennessee: '065400137',
    utah: '124001545',
    virginia: '044000037',
    vermont: '083000137',
    washington: '325070760',
    west_virginia: '051900366',
    wisconsin: '075000019',
    wyoming: '102001017',
  },
  'Wells Fargo': {
    alabama: '062000080',
    alaska: '125200057',
    arizona: '122105278',
    arkansas: '111900659',
    california: '121042882',
    colorado: '102000076',
    connecticut: '021101108',
    delaware: '031100869',
    florida: '063107513',
    georgia: '061000227',
    hawaii: '121042882',
    idaho: '124103799',
    illinois: '071101307',
    indiana: '074900275',
    iowa: '073000228',
    kansas: '101089292',
    kentucky: '121042882',
    louisiana: '121042882',
    maine: '121042882',
    maryland: '055003201',
    massachusetts: '121042882',
    michigan: '091101455',
    minnesota: '091000019',
    mississippi: '062203751',
    missouri: '113105449',
    montana: '092905278',
    nebraska: '104000058',
    nevada: '321270742',
    new_hampshire: '121042882',
    new_jersey: '021200025',
    new_mexico: '107002192',
    new_york: '026012881',
    north_carolina: '053000219',
    north_dakota: '091300010',
    ohio: '041215537',
    oklahoma: '121042882',
    oregon: '123006800',
    pennsylvania: '031000503',
    rhode_island: '121042882',
    south_carolina: '053207766',
    south_dakota: '091400046',
    tennessee: '064003768',
    texas: '111900659',
    utah: '124002971',
    vermont: '121042882',
    virginia: '051400549',
    washington: '125008547',
    west_virginia: '121042882',
    wisconsin: '075911988',
    wyoming: '102301092',
  },
  Citi: {
    california_northern: '321171184',
    california_southern: '322271724',
    connecticut: '221172610',
    florida: '266086554',
    district_of_columbia: '254070116',
    illinois: '271070801',
    maryland: '052002166',
    new_jersey: '021272655',
    new_york: '021000089',
    texas: '113193532',
    virginia: '254070116',
  },
  'U.S. Bank': {
    arizona: '122105155',
    arkansas: '082000549',
    california_northern: '121122676',
    california_southern: '122235821',
    colorado_aspen: '102101645',
    colorado: '102000021',
    idaho: '123103729',
    illinois_northern: '071904779',
    illinois_southern: '081202759',
    indiana: '074900783',
    iowa: '104000029',
    kansas: '101000187',
    kentucky_northern: '042100175',
    kentucky_western: '083900363',
    minnesota: '091000022',
    minnesota_east_grand_forks: '091215927',
    minnesota_moorhead: '091300023',
    missouri: '081000210',
    missouri_western: '101200453',
    montana: '092900383',
    nebraska: '104000029',
    nevada: '121201694',
    new_mexico: '107002312',
    north_carolina: '064103707',
    north_dakota: '091300023',
    ohio_cleveland: '041202582',
    ohio: '042000013',
    oregon: '123000220',
    south_dakota: '091408501',
    tennessee: '064000059',
    utah: '124302150',
    washington: '125000105',
    wisconsin: '075000022',
    wyoming: '307070115',
    alabama: '091000022',
    alaska: '091000022',
    connecticut: '091000022',
    delaware: '091000022',
    florida: '091000022',
    georgia: '091000022',
    hawaii: '091000022',
    maine: '091000022',
    maryland: '091000022',
    massachusetts: '091000022',
    michigan: '091000022',
    mississippi: '091000022',
    new_hampshire: '091000022',
    new_jersey: '091000022',
    new_york: '091000022',
    oklahoma: '091000022',
    pennsylvania: '091000022',
    rhode_island: '091000022',
    south_carolina: '091000022',
    texas: '091000022',
    vermont: '091000022',
    virginia: '091000022',
    west_virginia: '091000022',
  },
  GO2Bank: {
    alabama: '124303162',
    alaska: '124303162',
    arizona: '124303162',
    arkansas: '124303162',
    california: '124303162',
    colorado: '124303162',
    connecticut: '124303162',
    district_of_columbia: '124303162',
    delaware: '124303162',
    florida: '124303162',
    georgia: '124303162',
    hawaii: '124303162',
    idaho: '124303162',
    illinois: '124303162',
    indiana: '124303162',
    iowa: '124303162',
    kansas: '124303162',
    kentucky: '124303162',
    louisiana: '124303162',
    maine: '124303162',
    maryland: '124303162',
    massachusetts: '124303162',
    michigan: '124303162',
    minnesota: '124303162',
    mississippi: '124303162',
    missouri: '124303162',
    montana: '124303162',
    nebraska: '124303162',
    nevada: '124303162',
    new_hampshire: '124303162',
    new_jersey: '124303162',
    new_mexico: '124303162',
    new_york: '124303162',
    north_Carolina: '124303162',
    north_dakota: '124303162',
    ohio: '124303162',
    oklahoma: '124303162',
    oregon: '124303162',
    pennsylvania: '124303162',
    rhode_island: '124303162',
    south_carolina: '124303162',
    south_dakota: '124303162',
    tennessee: '124303162',
    texas: '124303162',
    utah: '124303162',
    vermont: '124303162',
    virginia: '124303162',
    washington: '124303162',
    west_virginia: '124303162',
    wisconsin: '124303162',
    wyoming: '124303162',
  },
  'Heritage Bank': {
    alabama: '091914710',
    alaska: '091914710',
    arizona: '091914710',
    arkansas: '091914710',
    california: '091914710',
    colorado: '091914710',
    connecticut: '091914710',
    district_of_columbia: '091914710',
    delaware: '091914710',
    florida: '091914710',
    georgia: '091914710',
    hawaii: '091914710',
    idaho: '091914710',
    illinois: '091914710',
    indiana: '091914710',
    iowa: '091914710',
    kansas: '091914710',
    kentucky: '091914710',
    louisiana: '091914710',
    maine: '091914710',
    maryland: '091914710',
    massachusetts: '091914710',
    michigan: '091914710',
    minnesota: '091914710',
    mississippi: '091914710',
    missouri: '091914710',
    montana: '091914710',
    nebraska: '091914710',
    nevada: '091914710',
    new_hampshire: '091914710',
    new_jersey: '091914710',
    new_mexico: '091914710',
    new_york: '091914710',
    north_Carolina: '091914710',
    north_dakota: '091914710',
    ohio: '091914710',
    oklahoma: '091914710',
    oregon: '091914710',
    pennsylvania: '091914710',
    rhode_island: '091914710',
    south_carolina: '091914710',
    south_dakota: '091914710',
    tennessee: '091914710',
    texas: '091914710',
    utah: '091914710',
    vermont: '091914710',
    virginia: '091914710',
    washington: '091914710',
    west_virginia: '091914710',
    wisconsin: '091914710',
    wyoming: '091914710',
  },
  'Navy Federal Credit Union': {
    alabama: '256074974',
    alaska: '256074974',
    arizona: '256074974',
    arkansas: '256074974',
    california: '256074974',
    colorado: '256074974',
    connecticut: '256074974',
    district_of_columbia: '256074974',
    delaware: '256074974',
    florida: '256074974',
    georgia: '256074974',
    hawaii: '256074974',
    idaho: '256074974',
    illinois: '256074974',
    indiana: '256074974',
    iowa: '256074974',
    kansas: '256074974',
    kentucky: '256074974',
    louisiana: '256074974',
    maine: '256074974',
    maryland: '256074974',
    massachusetts: '256074974',
    michigan: '256074974',
    minnesota: '256074974',
    mississippi: '256074974',
    missouri: '256074974',
    montana: '256074974',
    nebraska: '256074974',
    nevada: '256074974',
    new_hampshire: '256074974',
    new_jersey: '256074974',
    new_mexico: '256074974',
    new_york: '256074974',
    north_Carolina: '256074974',
    north_dakota: '256074974',
    ohio: '256074974',
    oklahoma: '256074974',
    oregon: '256074974',
    pennsylvania: '256074974',
    rhode_island: '256074974',
    south_carolina: '256074974',
    south_dakota: '256074974',
    tennessee: '256074974',
    texas: '256074974',
    utah: '256074974',
    vermont: '256074974',
    virginia: '256074974',
    washington: '256074974',
    west_virginia: '256074974',
    wisconsin: '256074974',
    wyoming: '256074974',
  },
  TIAA: {
    alabama: '063000225',
    alaska: '063000225',
    arizona: '063000225',
    arkansas: '063000225',
    california: '063000225',
    colorado: '063000225',
    connecticut: '063000225',
    district_of_columbia: '063000225',
    delaware: '063000225',
    florida: '063000225',
    georgia: '063000225',
    hawaii: '063000225',
    idaho: '063000225',
    illinois: '063000225',
    indiana: '063000225',
    iowa: '063000225',
    kansas: '063000225',
    kentucky: '063000225',
    louisiana: '063000225',
    maine: '063000225',
    maryland: '063000225',
    massachusetts: '063000225',
    michigan: '063000225',
    minnesota: '063000225',
    mississippi: '063000225',
    missouri: '063000225',
    montana: '063000225',
    nebraska: '063000225',
    nevada: '063000225',
    new_hampshire: '063000225',
    new_jersey: '063000225',
    new_mexico: '063000225',
    new_york: '063000225',
    north_Carolina: '063000225',
    north_dakota: '063000225',
    ohio: '063000225',
    oklahoma: '063000225',
    oregon: '063000225',
    pennsylvania: '063000225',
    rhode_island: '063000225',
    south_carolina: '063000225',
    south_dakota: '063000225',
    tennessee: '063000225',
    texas: '063000225',
    utah: '063000225',
    vermont: '063000225',
    virginia: '063000225',
    washington: '063000225',
    west_virginia: '063000225',
    wisconsin: '063000225',
    wyoming: '063000225',
  },
  'Goldman Sachs': {
    new_york: '026014601',
    utah: '124085260',
  },
  'Morgan Stanley': {
    california: '021272778',
    district_of_columbia: '021272778',
    florida: '021272778',
    georgia: '021272778',
    illinois: '021272778',
    maryland: '021272778',
    massachusetts: '021272778',
    new_york: '021272778',
    texas: '021272778',
  },
  'PNC Bank': {
    delaware: '031100089',
    district_of_columbia: '054000030',
    florida: '043002900',
    illinois: '071921891',
    kentucky: '083000108',
    michigan: '041000124',
    missouri: '071921891',
    new_jersey: '031207607',
    ohio: '042000398',
    ohio_youngstown: '043000096',
    wisconsin: '071921891',
  },
  'Capital One': {
    alabama: '051405515',
    alaska: '051405515',
    arizona: '051405515',
    arkansas: '051405515',
    california: '051405515',
    colorado: '051405515',
    connecticut: '051405515',
    district_of_columbia: '051405515',
    delaware: '051405515',
    florida: '051405515',
    georgia: '051405515',
    hawaii: '051405515',
    idaho: '051405515',
    illinois: '051405515',
    indiana: '051405515',
    iowa: '051405515',
    kansas: '051405515',
    kentucky: '051405515',
    louisiana: '051405515',
    maine: '051405515',
    maryland: '051405515',
    massachusetts: '051405515',
    michigan: '051405515',
    minnesota: '051405515',
    mississippi: '051405515',
    missouri: '051405515',
    montana: '051405515',
    nebraska: '051405515',
    nevada: '051405515',
    new_hampshire: '051405515',
    new_jersey: '051405515',
    new_mexico: '051405515',
    new_york: '051405515',
    north_Carolina: '051405515',
    north_dakota: '051405515',
    ohio: '051405515',
    oklahoma: '051405515',
    oregon: '051405515',
    pennsylvania: '051405515',
    rhode_island: '051405515',
    south_carolina: '051405515',
    south_dakota: '051405515',
    tennessee: '051405515',
    texas: '051405515',
    utah: '051405515',
    vermont: '051405515',
    virginia: '051405515',
    washington: '051405515',
    west_virginia: '051405515',
    wisconsin: '051405515',
    wyoming: '051405515',
  },
  'BB&T and SunTrust (Truist)': {
    alabama: '062203984',
    district_of_columbia: '054001547',
    florida: '263191387',
    georgia: '061113415',
    indiana: '083974289',
    kentucky: '083900680',
    maryland: '055003308',
    new_jersey: '031204710',
    north_carolina: '053101121',
    ohio: '042102267',
    pennsylvania: '031309123',
    south_carolina: '053201607',
    tennessee: '064208165',
    texas: '111017694',
    virginia: '051404260',
    west_virginia: '051503394',
  },
  'TD Bank': {
    connecticut: '011103093',
    distric_of_columbia: '054001725',
    florida: '067014822',
    maine: '211274450',
    massachusetts: '211370545',
    rhode_island: '211370545',
    maryland: '054001725',
    virginia: '054001725',
    new_jersey: '031201360',
    delaware: '031201360',
    new_york_metro_nyc: '026013673',
    new_york_northern: '021302567',
    north_carolina: '053902197',
    south_carolina: '053902197',
    pennsylvania: '036001808',
    vermont: '011600033',
  },
  'Ally Bank': {
    alabama: '124003116',
    alaska: '124003116',
    arizona: '124003116',
    arkansas: '124003116',
    california: '124003116',
    colorado: '124003116',
    connecticut: '124003116',
    district_of_columbia: '124003116',
    delaware: '124003116',
    florida: '124003116',
    georgia: '124003116',
    hawaii: '124003116',
    idaho: '124003116',
    illinois: '124003116',
    indiana: '124003116',
    iowa: '124003116',
    kansas: '124003116',
    kentucky: '124003116',
    louisiana: '124003116',
    maine: '124003116',
    maryland: '124003116',
    massachusetts: '124003116',
    michigan: '124003116',
    minnesota: '124003116',
    mississippi: '124003116',
    missouri: '124003116',
    montana: '124003116',
    nebraska: '124003116',
    nevada: '124003116',
    new_hampshire: '124003116',
    new_jersey: '124003116',
    new_mexico: '124003116',
    new_york: '124003116',
    north_Carolina: '124003116',
    north_dakota: '124003116',
    ohio: '124003116',
    oklahoma: '124003116',
    oregon: '124003116',
    pennsylvania: '124003116',
    rhode_island: '124003116',
    south_carolina: '124003116',
    south_dakota: '124003116',
    tennessee: '124003116',
    texas: '124003116',
    utah: '124003116',
    vermont: '124003116',
    virginia: '124003116',
    washington: '124003116',
    west_virginia: '124003116',
    wisconsin: '124003116',
    wyoming: '124003116',
  },
  HSBC: {
    alabama: '022000020',
    alaska: '022000020',
    arizona: '022000020',
    arkansas: '022000020',
    california: '022000020',
    colorado: '022000020',
    connecticut: '022000020',
    district_of_columbia: '022000020',
    delaware: '022000020',
    florida: '022000020',
    georgia: '022000020',
    hawaii: '022000020',
    idaho: '022000020',
    illinois: '022000020',
    indiana: '022000020',
    iowa: '022000020',
    kansas: '022000020',
    kentucky: '022000020',
    louisiana: '022000020',
    maine: '022000020',
    maryland: '022000020',
    massachusetts: '022000020',
    michigan: '022000020',
    minnesota: '022000020',
    mississippi: '022000020',
    missouri: '022000020',
    montana: '022000020',
    nebraska: '022000020',
    nevada: '022000020',
    new_hampshire: '022000020',
    new_jersey: '022000020',
    new_mexico: '022000020',
    new_york: '022000020',
    north_Carolina: '022000020',
    north_dakota: '022000020',
    ohio: '022000020',
    oklahoma: '022000020',
    oregon: '022000020',
    pennsylvania: '022000020',
    rhode_island: '022000020',
    south_carolina: '022000020',
    south_dakota: '022000020',
    tennessee: '022000020',
    texas: '022000020',
    utah: '022000020',
    vermont: '022000020',
    virginia: '022000020',
    washington: '022000020',
    west_virginia: '022000020',
    wisconsin: '022000020',
    wyoming: '022000020',
  },
  'Fifth Third Bank': {
    florida_north: '063113057',
    florida_central: '063109935',
    florida_south: '067091719',
    florida_tampa: '063103915',
    georgia: '263190812',
    illinois: '071923909',
    indiana_central: '074908594',
    indiana_southern: '086300041',
    kentucky_northern: '042100230',
    kentucky_central: '042101190',
    kentucky_southwestern: '083002342',
    michigan_northern: '072401404',
    michigan_eastern: '072405455',
    michigan_western: '072400052',
    missouri: '081019104',
    north_carolina: '053100737',
    ohio_cincinnati: '042000314',
    ohio_columbus: '044002161',
    ohio_northeastern: '041002711',
    ohio_northwestern: '041200050',
    ohio_western: '042202196',
    ohio_southern: '042207735',
    pennsylvania: '043018868',
    tennessee: '064103833',
  },
  KeyBank: {
    alaska: '125200879',
    colorado: '307070267',
    connecticut: '021300077',
    florida: '041001039',
    idaho: '124101555',
    indiana: '041001039',
    maine: '011200608',
    massachusetts: '021300077',
    michigan: '041001039',
    new_york: '021300077',
    ohio: '041001039',
    oregon: '123002011',
    pennsylvania: '021300077',
    utah: '124000737',
    vermont: '211672531',
    washington: '125000574',
  },
  'Regions Bank': {
    alabama: '062000019',
    arkansas: '082000109',
    florida: '063104668',
    georgia: '061101375',
    illinois: '071122661',
    indiana: '074014213',
    iowa: '073900438',
    kentucky: '083901744',
    louisiana: '065403626',
    mississippi: '065305436',
    missouri: '081001387',
    north_carolina: '053012029',
    south_carolina: '053201814',
    tennessee: '064000017',
    texas: '111900785',
    virginia: '051009296',
  },
  'Santander Bank': {
    delaware: '231372691',
    connecticut: '231372691',
    new_hampshire: '231372691',
    new_hampshire_before_2012: '011075150',
    rhode_island: '231372691',
    rhode_island_before_2012: '011075150',
    connecticut_before_2012: '011075150',
    maryland: '231372691',
    massachusetts: '231372691',
    massachusetts_before_2012: '011075150',
    new_jersey: '231372691',
    new_york: '231372691',
    pennsylvania: '231372691',
  },
  'M&T Bank': {
    connecticut: '022000046',
    maine: '022000046',
    massachusetts: '022000046',
    new_hampshire: '022000046',
    new_jersey: '022000046',
    new_york: '022000046',
    vermont: '022000046',
    delaware: '031302955',
    pennsylvania: '031302955',
    maryland: '052000113',
    virginia: '052000113',
    washington_dc: '052000113',
    west_virginia: '052000113',
  },
  Huntington: {
    '02': '041215032',
    '03': '044115090',
    '04': '041215016',
    '05': '041215032',
    '06': '044000024',
    '07': '044000024',
    '08': '044115090',
    '09': '044115090',
    '10': '041215032',
    '11': '044000024',
    '12': '041215032',
    '13': '044000024',
    '14': '042215060',
    '15': '072403473',
    '16': '044115090',
    '17': '072403473',
    '18': '072403473',
    '19': '051903761',
    '22': '051903761',
    '24': '051903761',
    '26': '041215016',
    '27': '051903761',
    '28': '044115090',
    '29': '057000697',
    '31': '044115090',
    '34': '074000078',
    '36': '072403473',
    '38': '072403473',
    '40': '074000078',
    '41': '051903761',
    '43': '074000078',
    '44': '042215060',
    '45': '042215060',
    '47': '041215016',
    '48': '044115090',
    '50': '041215032',
    '51': '044115090',
    '52': '051903761',
    '53': '051903761',
    '54': '041215016',
    '55': '074000078',
    '56': '051903761',
    '57': '051903761',
    '58': '041215032',
    '59': '041215032',
    '60': '044000024',
    '61': '044000024',
    '62': '044000024',
    '63': '041215032',
    '65': '042015422',
    '66': '041000153',
    '67': '044108641',
    '70': '041215016',
    '71': '042100191',
    '72': '042100191',
    '74': '042100191',
    '76': '044000024',
    '77': '044000024',
    '78': '041215032',
    '89': '044000024',
  },
  'BBVA USA': {
    alabama: '062001186',
    arizona: '122105744',
    california: '321170538',
    colorado: '107005319',
    florida: '063013924',
    new_mexico: '107000783',
    texas: '113010547',
    alaska: '062001186',
    arkansas: '062001186',
    connecticut: '062001186',
    delaware: '062001186',
    georgia: '062001186',
    hawaii: '062001186',
    idaho: '062001186',
    illinois: '062001186',
    indiana: '062001186',
    iowa: '062001186',
    kansas: '062001186',
    kentucky: '062001186',
    louisiana: '062001186',
    maine: '062001186',
    maryland: '062001186',
    massachusetts: '062001186',
    michigan: '062001186',
    minnesota: '062001186',
    mississippi: '062001186',
    missouri: '062001186',
    montana: '062001186',
    nebraska: '062001186',
    nevada: '062001186',
    new_hampshire: '062001186',
    new_jersey: '062001186',
    new_york: '062001186',
    north_carolina: '062001186',
    north_dakota: '062001186',
    ohio: '062001186',
    oklahoma: '062001186',
    oregon: '062001186',
    pennsylvania: '062001186',
    rhode_island: '062001186',
    south_carolina: '062001186',
    south_dakota: '062001186',
    tennessee: '062001186',
    utah: '062001186',
    vermont: '062001186',
    virginia: '062001186',
    washington: '062001186',
    west_virginia: '062001186',
    wisconsin: '062001186',
    wyoming: '062001186',
  },
  'Comerica Bank': {
    arizona: '121137522',
    california: '121137522',
    florida: '067012099',
    michigan: '072000096',
    texas: '111000753',
  },
  'Zions Bank': {
    alabama: '124000054',
    alaska: '124000054',
    arizona: '124000054',
    arkansas: '124000054',
    california: '124000054',
    colorado: '124000054',
    connecticut: '124000054',
    district_of_columbia: '124000054',
    delaware: '124000054',
    florida: '124000054',
    georgia: '124000054',
    hawaii: '124000054',
    idaho: '124000054',
    illinois: '124000054',
    indiana: '124000054',
    iowa: '124000054',
    kansas: '124000054',
    kentucky: '124000054',
    louisiana: '124000054',
    maine: '124000054',
    maryland: '124000054',
    massachusetts: '124000054',
    michigan: '124000054',
    minnesota: '124000054',
    mississippi: '124000054',
    missouri: '124000054',
    montana: '124000054',
    nebraska: '124000054',
    nevada: '124000054',
    new_hampshire: '124000054',
    new_jersey: '124000054',
    new_mexico: '124000054',
    new_york: '124000054',
    north_Carolina: '124000054',
    north_dakota: '124000054',
    ohio: '124000054',
    oklahoma: '124000054',
    oregon: '124000054',
    pennsylvania: '124000054',
    rhode_island: '124000054',
    south_carolina: '124000054',
    south_dakota: '124000054',
    tennessee: '124000054',
    texas: '124000054',
    utah: '124000054',
    vermont: '124000054',
    virginia: '124000054',
    washington: '124000054',
    west_virginia: '124000054',
    wisconsin: '124000054',
    wyoming: '124000054',
  },
  'Synovus Bank': {
    alabama: '061100606',
    alaska: '061100606',
    arizona: '061100606',
    arkansas: '061100606',
    california: '061100606',
    colorado: '061100606',
    connecticut: '061100606',
    district_of_columbia: '061100606',
    delaware: '061100606',
    florida: '061100606',
    georgia: '061100606',
    hawaii: '061100606',
    idaho: '061100606',
    illinois: '061100606',
    indiana: '061100606',
    iowa: '061100606',
    kansas: '061100606',
    kentucky: '061100606',
    louisiana: '061100606',
    maine: '061100606',
    maryland: '061100606',
    massachusetts: '061100606',
    michigan: '061100606',
    minnesota: '061100606',
    mississippi: '061100606',
    missouri: '061100606',
    montana: '061100606',
    nebraska: '061100606',
    nevada: '061100606',
    new_hampshire: '061100606',
    new_jersey: '061100606',
    new_mexico: '061100606',
    new_york: '061100606',
    north_Carolina: '061100606',
    north_dakota: '061100606',
    ohio: '061100606',
    oklahoma: '061100606',
    oregon: '061100606',
    pennsylvania: '061100606',
    rhode_island: '061100606',
    south_carolina: '061100606',
    south_dakota: '061100606',
    tennessee: '061100606',
    texas: '061100606',
    utah: '061100606',
    vermont: '061100606',
    virginia: '061100606',
    washington: '061100606',
    west_virginia: '061100606',
    wisconsin: '061100606',
    wyoming: '061100606',
  },
};

export const mockJsonData = {
  first_name: 'John',
  middle_name: 'A',
  last_name: 'Doe',
  gender: 'Male',
  date_of_birth: '05-05-1975',
  age: '48',
  phone_number: '512-512-5125',
  ssn: '987-65-4321',
  email: 'johndoe@example.com',
  address: '301 W 2nd St',
  state: 'Texas',
  zip_code: '78701',
  city: 'Austin',
  county: 'Travis County',
  height: "5'10",
  weight: '155 lb',
  country_of_birth: 'United States Of America',
  state_of_birth: 'California',
  employment_status: 'Employed',
  occupation: 'Garbage Truck Driver',
  married: 'Yes',
  taxes_filing_status: 'Married Filing Jointly',
  household_size: '2',
  immigration_status: 'Citizen',
  bank_name: 'Wells Fargo',
  account_type: 'Checking',
  routing_number: '111900659',
  account_number: '1234567890',
  beneficiary_full_name: 'Jane Doe',
  beneficiary_relationship: 'Spouse',
  name_of_account_holder: 'John Doe',
  current_insurance: 'No',
  coverage_reason: 'Moved recently',
  plan_type: 'Family',
  tobacco_use: 'No',
  additional_insured: 'Yes',
  additional_insured_list: [
    {
      'Full Name': 'Jane Doe',
      'Relationship To Primary': 'spouse',
      'Date Of Birth': '07-06-1985',
      Age: '37',
      Gender: 'Female',
      SSN: '123-45-6789',
      'Country Of Birth': 'Romania',
      'Employment Status': 'Stay-at-home',
      Height: "5'1",
      Weight: '110 lb',
      'Beneficiary Full Name': 'John Doe',
      'Beneficiary Relationship': 'Husband',
      Notes: 'Write some notes here...',
    },
  ],
  annual_household_income: '$25,000',
  monthly_budget: '$150',
  carrier_name: 'Oscar',
  plan_name:
    'Bronze Classic- $4700 Ded ($3 Preferred Generic Drugs + $0 Virtual Urgent Care Visits with Select Providers) - EPO',
  monthly_health_premium: '$0',
  pcp_copay: '$70',
  specialist_copay: '$125',
  generic_meds_copay: '$3',
  annual_deductible: '$4,700',
  max_out_of_pocket: '$9,100',
  health_unsubsidized: '$990.67',
  death_benefit: '$250,000',
  qualified_subsidy: '$1,047',
  life_adb_provider: 'Americo',
  life_total_cost: '$96',
  life_health_unsubsidized: '$1,086.67',
  monthly_grand_total: '$96.00',
  applying_for_coverage: '2',
  pre_existing_conditions: 'No',
  medications: 'Yes',
  medications_list: 'Adderall 30MG',
  medical_history: 'No history',
  preferred_doctors: 'Yes',
  preferred_doctors_name: 'Dr. Lino Fernandez',
  americo_premium: '$48',
  claims_dependents: 'No',
};
