export const isBrowser = () => typeof window !== 'undefined';

export const toTitleCase = (string: string) => {
  string = string.replace(/_/g, ' ');
  return string.replace(/\w\S*/g, function (text: string) {
    return text.charAt(0).toUpperCase() + text.substring(1).toLowerCase();
  });
};

export const unitedStates = [
  { label: 'Alabama - AL', value: 'alabama' },
  { label: 'Alaska - AK', value: 'alaska' },
  { label: 'Arizona - AZ', value: 'arizona' },
  { label: 'Arkansas - AR', value: 'arkansas' },
  { label: 'California - CA', value: 'california' },
  { label: 'Colorado - CO', value: 'colorado' },
  { label: 'Connecticut - CT', value: 'connecticut' },
  { label: 'Delaware - DE', value: 'delaware' },
  { label: 'Florida - FL', value: 'florida' },
  { label: 'Georgia - GA', value: 'georgia' },
  { label: 'Hawaii - HI', value: 'hawaii' },
  { label: 'Idaho - ID', value: 'idaho' },
  { label: 'Illinois - IL', value: 'illinois' },
  { label: 'Indiana - IN', value: 'indiana' },
  { label: 'Iowa - IA', value: 'iowa' },
  { label: 'Kansas - KS', value: 'kansas' },
  { label: 'Kentucky - KY', value: 'kentucky' },
  { label: 'Louisiana - LA', value: 'louisiana' },
  { label: 'Maine - ME', value: 'maine' },
  { label: 'Maryland - MD', value: 'maryland' },
  { label: 'Massachusetts - MA', value: 'massachusetts' },
  { label: 'Michigan - MI', value: 'michigan' },
  { label: 'Minnesota - MN', value: 'minnesota' },
  { label: 'Mississippi - MS', value: 'mississippi' },
  { label: 'Missouri - MO', value: 'missouri' },
  { label: 'Montana - MT', value: 'montana' },
  { label: 'Nebraska - NE', value: 'nebraska' },
  { label: 'Nevada - NV', value: 'nevada' },
  { label: 'New Hampshire - NH', value: 'new_hampshire' },
  { label: 'New Jersey - NJ', value: 'new_jersey' },
  { label: 'New Mexico - NM', value: 'new_mexico' },
  { label: 'New York - NY', value: 'new_york' },
  { label: 'North Carolina - NC', value: 'north_Carolina' },
  { label: 'North Dakota - ND', value: 'north_dakota' },
  { label: 'Ohio - OH', value: 'ohio' },
  { label: 'Oklahoma - OK', value: 'oklahoma' },
  { label: 'Oregon - OR', value: 'oregon' },
  { label: 'Pennsylvania - PA', value: 'pennsylvania' },
  { label: 'Rhode Island - RI', value: 'rhode_island' },
  { label: 'South Carolina - SC', value: 'south_carolina' },
  { label: 'South Dakota - SD', value: 'south_dakota' },
  { label: 'Tennessee - TN', value: 'tennessee' },
  { label: 'Texas - TX', value: 'texas' },
  { label: 'Utah - UT', value: 'utah' },
  { label: 'Vermont - VT', value: 'vermont' },
  { label: 'Virginia - VA', value: 'virginia' },
  { label: 'Washington - WA', value: 'washington' },
  { label: 'West Virginia - WV', value: 'west_virginia' },
  { label: 'Wisconsin - WI', value: 'wisconsin' },
  { label: 'Wyoming - WY', value: 'wyoming' },
  { label: 'Puerto Rico - PR', value: 'puerto_rico' },
];

export const preferredCarriers = {
  alabama: ['Aetna', 'UnitedHealthcare (UHC)'],
  alaska: ['None'],
  arizona: ['Aetna', 'Ambetter', 'Cigna', 'Oscar', 'UnitedHealthcare (UHC)'],
  arkansas: ['None'],
  california: ['Aetna', 'Molina', 'Oscar'],
  colorado: ['Cigna', 'Friday Health Plans', 'Oscar', 'UnitedHealthcare (UHC)'],
  connecticut: ['None'],
  delaware: ['None'],
  florida: ['Aetna', 'Ambetter', 'Avmed', 'Cigna', 'Florida Blue', 'Molina', 'Oscar', 'UnitedHealthcare (UHC)'],
  georgia: ['Ambetter', 'Cigna', 'Friday Health Plans', 'Oscar', 'UnitedHealthcare (UHC)'],
  hawaii: ['None'],
  idaho: ['None'],
  illinois: ['Aetna', 'Ambetter', 'Cigna', 'Molina', 'Oscar', 'UnitedHealthcare (UHC)'],
  indiana: ['Aetna', 'Ambetter'],
  iowa: ['Oscar'],
  kansas: ['Aetna', 'Cigna', 'Oscar'],
  kentucky: ['None'],
  louisiana: ['Ambetter', 'Arizona', 'UnitedHealthcare (UHC)'],
  maine: ['None'],
  maryland: ['UnitedHealthcare (UHC)'],
  massachusetts: ['None'],
  michigan: ['Aetna', 'Ambetter', 'Molina', 'Oscar', 'UnitedHealthcare (UHC)'],
  minnesota: ['None'],
  mississippi: ['Ambetter', 'Cigna', 'Molina', 'UnitedHealthcare (UHC)'],
  missouri: ['Cigna', 'Oscar', 'UnitedHealthcare (UHC)'],
  montana: ['None'],
  nebraska: ['Ambetter', 'Oscar'],
  nevada: ['None'],
  new_hampshire: ['None'],
  new_jersey: ['Aetna', 'Ambetter', 'Oscar', 'UnitedHealthcare (UHC)'],
  new_mexico: ['Aetna', 'Ambetter', 'Friday Health Plans', 'Molina'],
  new_york: ['None'],
  north_Carolina: ['Aetna', 'Ambetter', 'Cigna', 'Friday Health Plans', 'Oscar', 'UnitedHealthcare (UHC)'],
  north_dakota: ['None'],
  ohio: ['Aetna', 'Ambetter', 'Molina', 'Oscar', 'UnitedHealthcare (UHC)'],
  oklahoma: ['Aetna', 'Ambetter', 'Friday Health Plans', 'Oscar', 'UnitedHealthcare (UHC)'],
  oregon: ['None'],
  pennsylvania: ['Cigna', 'Oscar'],
  rhode_island: ['None'],
  south_carolina: ['Aetna', 'Ambetter', 'BlueCross BlueShield', 'Cigna', 'Molina', 'UnitedHealthcare (UHC)'],
  south_dakota: ['None'],
  tennessee: ['Aetna', 'Ambetter', 'Arizona', 'Oscar', 'UnitedHealthcare (UHC)'],
  texas: [
    'Aetna',
    'Ambetter',
    'BlueCross BlueShield',
    'Cigna',
    'Friday Health Plans',
    'Molina',
    'Oscar',
    'UnitedHealthcare (UHC)',
  ],
  utah: ['Aetna', 'Cigna', 'Molina', 'UnitedHealthcare (UHC)'],
  vermont: ['None'],
  virginia: ['Aetna', 'Cigna', 'Oscar', 'UnitedHealthcare (UHC)'],
  washington: ['None'],
  west_virginia: ['None'],
  wisconsin: ['None'],
  wyoming: ['None'],
  puerto_rico: ['None'],
};

//   "None",
//   "Aetna",
//   "Ambetter",
//   "Arizona",
//   "Avmed",
//   "BlueCross BlueShield",
//   "Cigna",
//   "Florida Blue",
//   "Friday Health Plans",
//   "Molina",
//   "Oscar",
//   "UnitedHealthcare (UHC)"
