export const isBrowser = () => typeof window !== 'undefined';

export const states = [
  { label: 'Alabama [AL]', value: 'Alabama [AL]' },
  { label: 'Alaska [AK]', value: 'Alaska [AK]' },
  { label: 'Arizona [AZ]', value: 'Arizona [AZ]' },
  { label: 'Arkansas [AR]', value: 'Arkansas [AR]' },
  { label: 'California [CA]', value: 'California [CA]' },
  { label: 'Colorado [CO]', value: 'Colorado [CO]' },
  { label: 'Connecticut [CT]', value: 'Connecticut [CT]' },
  { label: 'Delaware [DE]', value: 'Delaware [DE]' },
  { label: 'Florida [FL]', value: 'Florida [FL]' },
  { label: 'Georgia [GA]', value: 'Georgia [GA]' },
  { label: 'Hawaii [HI]', value: 'Hawaii [HI]' },
  { label: 'Idaho [ID]', value: 'Idaho [ID]' },
  { label: 'Illinois [IL]', value: 'Illinois [IL]' },
  { label: 'Indiana [IN]', value: 'Indiana [IN]' },
  { label: 'Iowa [IA]', value: 'Iowa [IA]' },
  { label: 'Kansas [KS]', value: 'Kansas [KS]' },
  { label: 'Kentucky [KY]', value: 'Kentucky [KY]' },
  { label: 'Louisiana [LA]', value: 'Louisiana [LA]' },
  { label: 'Maine [ME]', value: 'Maine [ME]' },
  { label: 'Maryland [MD]', value: 'Maryland [MD]' },
  { label: 'Massachusetts [MA]', value: 'Massachusetts [MA]' },
  { label: 'Michigan [MI]', value: 'Michigan [MI]' },
  { label: 'Minnesota [MN]', value: 'Minnesota [MN]' },
  { label: 'Mississippi [MS]', value: 'Mississippi [MS]' },
  { label: 'Missouri [MO]', value: 'Missouri [MO]' },
  { label: 'Montana [MT]', value: 'Montana [MT]' },
  { label: 'Nebraska [NE]', value: 'Nebraska [NE]' },
  { label: 'Nevada [NV]', value: 'Nevada [NV]' },
  { label: 'New Hampshire [NH]', value: 'New Hampshire [NH]' },
  { label: 'New Jersey [NJ]', value: 'New Jersey [NJ]' },
  { label: 'New Mexico [NM]', value: 'New Mexico [NM]' },
  { label: 'New York [NY]', value: 'New York [NY]' },
  { label: 'North Carolina [NC]', value: 'North Carolina [NC]' },
  { label: 'North Dakota [ND]', value: 'North Dakota [ND]' },
  { label: 'Ohio [OH]', value: 'Ohio [OH]' },
  { label: 'Oklahoma [OK]', value: 'Oklahoma [OK]' },
  { label: 'Oregon [OR]', value: 'Oregon [OR]' },
  { label: 'Pennsylvania [PA]', value: 'Pennsylvania [PA]' },
  { label: 'Rhode Island [RI]', value: 'Rhode Island [RI]' },
  { label: 'South Carolina [SC]', value: 'South Carolina [SC]' },
  { label: 'South Dakota [SD]', value: 'South Dakota [SD]' },
  { label: 'Tennessee [TN]', value: 'Tennessee [TN]' },
  { label: 'Texas [TX]', value: 'Texas [TX]' },
  { label: 'Utah [UT]', value: 'Utah [UT]' },
  { label: 'Vermont [VT]', value: 'Vermont [VT]' },
  { label: 'Virginia [VA]', value: 'Virginia [VA]' },
  { label: 'Washington [WA]', value: 'Washington [WA]' },
  { label: 'West Virginia [WV]', value: 'West Virginia [WV]' },
  { label: 'Wisconsin [WI]', value: 'Wisconsin [WI]' },
  { label: 'Wyoming [WY]', value: 'Wyoming [WY]' },
  { label: 'Puerto Rico [PR]', value: 'Puerto Rico [PR]' },
];
